# Code generated by codegen/generate.ts — DO NOT EDIT.

class HeraldError(Exception):
    def __init__(self, code: str, message: str, status: int = 0) -> None:
        super().__init__(f"{code}: {message}")
        self.code = code
        self.message = message
        self.status = status
