<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class AuditNamespace
{
    public function __construct(
        private readonly HttpTransport $t,
        private readonly string $tenantId,
    ) {}

    public function query(
        ?string $operation = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?string $actor = null,
        ?string $result = null,
        ?string $since = null,
        ?string $until = null,
        ?int $limit = null,
    ): array {
        $params = $this->buildParams($operation, $resourceType, $resourceId, $actor, $result, $since, $until);
        if ($limit !== null) $params[] = "limit={$limit}";
        $path = $this->basePath();
        if ($params) $path .= '?' . implode('&', $params);
        return $this->t->request('GET', $path);
    }

    public function count(
        ?string $operation = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
        ?string $actor = null,
        ?string $result = null,
        ?string $since = null,
        ?string $until = null,
    ): int {
        $params = $this->buildParams($operation, $resourceType, $resourceId, $actor, $result, $since, $until);
        $path = $this->basePath() . '/count';
        if ($params) $path .= '?' . implode('&', $params);
        $data = $this->t->request('GET', $path);
        return $data['count'];
    }

    private function basePath(): string
    {
        return '/admin/tenants/' . rawurlencode($this->tenantId) . '/audit';
    }

    /**
     * @return string[]
     */
    private function buildParams(?string $op, ?string $rt, ?string $ri, ?string $actor, ?string $result, ?string $since, ?string $until): array
    {
        $params = [];
        if ($op !== null) $params[] = 'operation=' . rawurlencode($op);
        if ($rt !== null) $params[] = 'resource_type=' . rawurlencode($rt);
        if ($ri !== null) $params[] = 'resource_id=' . rawurlencode($ri);
        if ($actor !== null) $params[] = 'actor=' . rawurlencode($actor);
        if ($result !== null) $params[] = 'result=' . rawurlencode($result);
        if ($since !== null) $params[] = 'since=' . rawurlencode($since);
        if ($until !== null) $params[] = 'until=' . rawurlencode($until);
        return $params;
    }
}
