<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class BlockNamespace
{
    public function __construct(private readonly HttpTransport $t) {}

    public function block(string $userId, string $blockedId): void
    {
        $this->t->request('POST', '/blocks', ['user_id' => $userId, 'blocked_id' => $blockedId]);
    }

    public function unblock(string $userId, string $blockedId): void
    {
        $this->t->request('DELETE', '/blocks', ['user_id' => $userId, 'blocked_id' => $blockedId]);
    }

    public function list(string $userId): array
    {
        $data = $this->t->request('GET', '/blocks/' . rawurlencode($userId));
        return $data['blocked'];
    }
}
