<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class EventNamespace
{
    public function __construct(private readonly HttpTransport $t) {}

    public function publish(string $streamId, string $sender, string $body, mixed $meta = null, ?string $parentId = null, ?string $excludeConnection = null): array
    {
        $req = ['sender' => $sender, 'body' => $body];
        if ($meta !== null) $req['meta'] = $meta;
        if ($parentId !== null) $req['parent_id'] = $parentId;
        if ($excludeConnection !== null) $req['exclude_connection'] = $excludeConnection;
        return $this->t->request('POST', '/streams/' . rawurlencode($streamId) . '/events', $req);
    }

    public function list(string $streamId, ?int $before = null, ?int $after = null, ?int $limit = null, ?string $thread = null): array
    {
        $params = [];
        if ($before !== null) $params[] = "before={$before}";
        if ($after !== null) $params[] = "after={$after}";
        if ($limit !== null) $params[] = "limit={$limit}";
        if ($thread !== null) $params[] = 'thread=' . rawurlencode($thread);
        $qs = $params ? '?' . implode('&', $params) : '';
        return $this->t->request('GET', '/streams/' . rawurlencode($streamId) . "/events{$qs}");
    }

    public function delete(string $streamId, string $eventId): void
    {
        $this->t->request('DELETE', '/streams/' . rawurlencode($streamId) . '/events/' . rawurlencode($eventId));
    }

    public function edit(string $streamId, string $eventId, string $body): void
    {
        $this->t->request('PATCH', '/streams/' . rawurlencode($streamId) . '/events/' . rawurlencode($eventId), ['body' => $body]);
    }

    public function getReactions(string $streamId, string $eventId): array
    {
        $data = $this->t->request('GET', '/streams/' . rawurlencode($streamId) . '/events/' . rawurlencode($eventId) . '/reactions');
        return $data['reactions'];
    }

    public function trigger(string $streamId, string $event, mixed $data = null, ?int $excludeConnection = null): void
    {
        $body = ['event' => $event];
        if ($data !== null) $body['data'] = $data;
        if ($excludeConnection !== null) $body['exclude_connection'] = $excludeConnection;
        $this->t->request('POST', '/streams/' . rawurlencode($streamId) . '/trigger', $body);
    }
}
