<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class MemberNamespace
{
    public function __construct(private readonly HttpTransport $t) {}

    public function add(string $streamId, string $userId, string $role = 'member'): array
    {
        return $this->t->request('POST', '/streams/' . rawurlencode($streamId) . '/members', ['user_id' => $userId, 'role' => $role]);
    }

    public function list(string $streamId): array
    {
        $data = $this->t->request('GET', '/streams/' . rawurlencode($streamId) . '/members');
        return $data['members'];
    }

    public function remove(string $streamId, string $userId): void
    {
        $this->t->request('DELETE', '/streams/' . rawurlencode($streamId) . '/members/' . rawurlencode($userId));
    }

    public function update(string $streamId, string $userId, string $role): void
    {
        $this->t->request('PATCH', '/streams/' . rawurlencode($streamId) . '/members/' . rawurlencode($userId), ['role' => $role]);
    }
}
