<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class PresenceNamespace
{
    public function __construct(private readonly HttpTransport $t) {}

    public function getUser(string $userId): array
    {
        return $this->t->request('GET', '/presence/' . rawurlencode($userId));
    }

    public function getStream(string $streamId): array
    {
        $data = $this->t->request('GET', '/streams/' . rawurlencode($streamId) . '/presence');
        return $data['members'];
    }

    public function getCursors(string $streamId): array
    {
        $data = $this->t->request('GET', '/streams/' . rawurlencode($streamId) . '/cursors');
        return $data['cursors'];
    }

    public function getBulk(array $userIds): array
    {
        $ids = implode(',', array_map('urlencode', $userIds));
        $data = $this->t->request('GET', "/presence?user_ids={$ids}");
        return $data['users'];
    }

    public function setOverride(string $userId, array $options): array
    {
        return $this->t->request('POST', '/presence/' . urlencode($userId), $options);
    }
}
