<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class StreamNamespace
{
    public function __construct(private readonly HttpTransport $t) {}

    public function create(string $id, string $name, mixed $meta = null, bool $public = false): array
    {
        $body = ['id' => $id, 'name' => $name];
        if ($meta !== null) $body['meta'] = $meta;
        if ($public) $body['public'] = true;
        return $this->t->request('POST', '/streams', $body);
    }

    public function get(string $id): array
    {
        return $this->t->request('GET', '/streams/' . rawurlencode($id));
    }

    public function update(string $id, ?string $name = null, mixed $meta = null, ?bool $archived = null): void
    {
        $body = [];
        if ($name !== null) $body['name'] = $name;
        if ($meta !== null) $body['meta'] = $meta;
        if ($archived !== null) $body['archived'] = $archived;
        $this->t->request('PATCH', '/streams/' . rawurlencode($id), $body);
    }

    public function list(): array
    {
        $data = $this->t->request('GET', '/streams');
        return $data['streams'];
    }

    public function delete(string $id): void
    {
        $this->t->request('DELETE', '/streams/' . rawurlencode($id));
    }
}
