<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin\Namespaces;

use Herald\Admin\HttpTransport;

class TenantNamespace
{
    public function __construct(private readonly HttpTransport $t) {}

    public function create(string $name, ?string $plan = null): array
    {
        $body = ['name' => $name];
        if ($plan !== null) $body['plan'] = $plan;
        return $this->t->request('POST', '/admin/tenants', $body);
    }

    public function list(): array
    {
        $data = $this->t->request('GET', '/admin/tenants');
        return $data['tenants'];
    }

    public function get(string $id): array
    {
        return $this->t->request('GET', '/admin/tenants/' . rawurlencode($id));
    }

    public function update(string $id, ?string $name = null, ?string $plan = null, ?int $eventTtlDays = null): void
    {
        $body = [];
        if ($name !== null) $body['name'] = $name;
        if ($plan !== null) $body['plan'] = $plan;
        if ($eventTtlDays !== null) $body['event_ttl_days'] = $eventTtlDays;
        $this->t->request('PATCH', '/admin/tenants/' . rawurlencode($id), $body);
    }

    public function delete(string $id): void
    {
        $this->t->request('DELETE', '/admin/tenants/' . rawurlencode($id));
    }

    public function createToken(string $tenantId, ?string $scope = null): string
    {
        $body = $scope !== null ? ['scope' => $scope] : null;
        $data = $this->t->request('POST', '/admin/tenants/' . rawurlencode($tenantId) . '/tokens', $body);
        return $data['token'];
    }

    public function deleteToken(string $tenantId, string $token): void
    {
        $this->t->request('DELETE', '/admin/tenants/' . rawurlencode($tenantId) . '/tokens/' . rawurlencode($token));
    }

    public function listTokens(string $tenantId): array
    {
        $data = $this->t->request('GET', '/admin/tenants/' . rawurlencode($tenantId) . '/tokens');
        return $data['tokens'];
    }

    public function listStreams(string $tenantId): array
    {
        $data = $this->t->request('GET', '/admin/tenants/' . rawurlencode($tenantId) . '/streams');
        return $data['streams'];
    }

    public function purgeData(string $tenantId): array
    {
        return $this->t->request('DELETE', '/admin/tenants/' . rawurlencode($tenantId) . '/data');
    }
}
