<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin;

use Herald\Admin\Namespaces\StreamNamespace;
use Herald\Admin\Namespaces\MemberNamespace;
use Herald\Admin\Namespaces\EventNamespace;
use Herald\Admin\Namespaces\PresenceNamespace;
use Herald\Admin\Namespaces\TenantNamespace;
use Herald\Admin\Namespaces\AuditNamespace;
use Herald\Admin\Namespaces\BlockNamespace;

class ChatNamespaces
{
    public function __construct(
        public readonly BlockNamespace $blocks,
    ) {}
}

class HeraldAdmin
{
    public readonly StreamNamespace $streams;
    public readonly MemberNamespace $members;
    public readonly EventNamespace $events;
    public readonly TenantNamespace $tenants;
    public readonly ?AuditNamespace $audit;
    public readonly PresenceNamespace $presence;
    public readonly ChatNamespaces $chat;
    private readonly HttpTransport $transport;

    public function __construct(
        string $url,
        ?string $token = null,
        ?string $key = null,
        ?string $secret = null,
        ?string $tenantId = null,
    ) {
        $this->transport = new HttpTransport($url, $token, $key, $secret);
        $this->streams = new StreamNamespace($this->transport);
        $this->members = new MemberNamespace($this->transport);
        $this->events = new EventNamespace($this->transport);
        $this->tenants = new TenantNamespace($this->transport);
        $this->presence = new PresenceNamespace($this->transport);
        $this->chat = new ChatNamespaces(new BlockNamespace($this->transport));
        $this->audit = $tenantId !== null ? new AuditNamespace($this->transport, $tenantId) : null;
    }

    public function health(): array
    {
        return $this->transport->request('GET', '/health');
    }

    public function connections(): array
    {
        return $this->transport->request('GET', '/admin/connections');
    }

    public function adminEvents(?int $limit = null): array
    {
        $path = '/admin/events';
        if ($limit !== null) $path .= "?limit={$limit}";
        return $this->transport->request('GET', $path);
    }

    public function errors(?int $limit = null, ?string $category = null): array
    {
        $params = [];
        if ($limit !== null) $params[] = "limit={$limit}";
        if ($category !== null) $params[] = 'category=' . rawurlencode($category);
        $path = '/admin/errors';
        if ($params) $path .= '?' . implode('&', $params);
        return $this->transport->request('GET', $path);
    }

    public function stats(): array
    {
        return $this->transport->request('GET', '/admin/stats');
    }
}
