<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin;

class HeraldError extends \RuntimeException
{
    public readonly string $code;
    public readonly int $status;

    public function __construct(string $code, string $message, int $status = 0)
    {
        parent::__construct("{$code}: {$message}");
        $this->code = $code;
        $this->status = $status;
    }
}
