<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

namespace Herald\Admin;

class HttpTransport
{
    private string $baseUrl;
    private string $authHeader;
    private int $timeoutSecs;

    private const HTTP_ERROR_CODES = [
        400 => 'BAD_REQUEST', 401 => 'UNAUTHORIZED', 403 => 'FORBIDDEN',
        404 => 'NOT_FOUND', 409 => 'CONFLICT', 429 => 'RATE_LIMITED',
        500 => 'INTERNAL', 503 => 'UNAVAILABLE',
    ];

    public function __construct(string $baseUrl, ?string $token = null, ?string $key = null, ?string $secret = null, int $timeoutSecs = 30)
    {
        $this->baseUrl = rtrim($baseUrl, '/');
        if ($key !== null && $secret !== null) {
            $this->authHeader = 'Basic ' . base64_encode("{$key}:{$secret}");
        } elseif ($token !== null) {
            $this->authHeader = "Bearer {$token}";
        } else {
            throw new \InvalidArgumentException('Provide either token or key+secret');
        }
        $this->timeoutSecs = $timeoutSecs;
    }

    /**
     * @return mixed
     */
    public function request(string $method, string $path, mixed $body = null): mixed
    {
        $url = $this->baseUrl . $path;
        $headers = ["Authorization: {$this->authHeader}"];
        $payload = null;

        if ($body !== null) {
            $payload = json_encode($body, JSON_THROW_ON_ERROR);
            $headers[] = 'Content-Type: application/json';
        }

        $opts = [
            'http' => [
                'method' => strtoupper($method),
                'header' => implode("\r\n", $headers),
                'timeout' => $this->timeoutSecs,
                'ignore_errors' => true,
            ],
        ];
        if ($payload !== null) {
            $opts['http']['content'] = $payload;
        }

        $context = stream_context_create($opts);
        $raw = @file_get_contents($url, false, $context);

        // Parse status code from response headers
        $statusCode = 0;
        $responseHeaders = function_exists('http_get_last_response_headers')
            ? (http_get_last_response_headers() ?? [])
            : ($http_response_header ?? []);
        foreach ($responseHeaders as $hdr) {
            if (preg_match('/^HTTP\/[\d.]+ (\d+)/', $hdr, $m)) {
                $statusCode = (int)$m[1];
            }
        }

        if ($raw === false && $statusCode === 0) {
            throw new HeraldError('INTERNAL', 'Request failed: unable to connect');
        }

        if ($statusCode >= 400) {
            $code = self::HTTP_ERROR_CODES[$statusCode] ?? 'INTERNAL';
            $message = "HTTP {$statusCode}";
            if ($raw) {
                $data = json_decode($raw, true);
                if (is_array($data) && isset($data['error'])) {
                    $message = $data['error'];
                } elseif ($raw !== '') {
                    $message = $raw;
                }
            }
            throw new HeraldError($code, $message, $statusCode);
        }

        if ($statusCode === 204) {
            return null;
        }

        if ($raw === '' || $raw === false) {
            return null;
        }

        return json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
    }
}
