// Code generated by codegen/generate.ts — DO NOT EDIT.

import type { HttpTransport } from "../transport.js";
import type { MemberPresenceEntry, UserPresence } from "../types.js";

export class PresenceNamespace {
  constructor(private transport: HttpTransport) {}

  async getUser(userId: string): Promise<UserPresence> {
    return this.transport.request<UserPresence>(
      "GET",
      `/presence/${encodeURIComponent(userId)}`,
    );
  }

  async getStream(streamId: string): Promise<MemberPresenceEntry[]> {
    const resp = await this.transport.request<{ members: MemberPresenceEntry[] }>(
      "GET",
      `/streams/${encodeURIComponent(streamId)}/presence`,
    );
    return resp.members;
  }

  async getBulk(userIds: string[]): Promise<UserPresence[]> {
    const ids = userIds.map(encodeURIComponent).join(",");
    const resp = await this.transport.request<{ users: UserPresence[] }>(
      "GET",
      `/presence?user_ids=${ids}`,
    );
    return resp.users;
  }

  async setOverride(userId: string, options: { status: string; until?: string }): Promise<UserPresence> {
    return this.transport.request<UserPresence>(
      "POST",
      `/presence/${encodeURIComponent(userId)}`,
      options,
    );
  }
}
