// Code generated by codegen — DO NOT EDIT.
// Intermediate representation for Herald admin SDK code generation.

/** A single method parameter (path, query, or body field). */
export interface Param {
  /** Parameter name as it appears in the SDK method signature (camelCase). */
  name: string;
  /** Wire name (snake_case) used in JSON body or URL path/query. */
  wireName: string;
  /** TypeScript type string (e.g. "string", "number", "unknown"). */
  tsType: string;
  /** Go type string (e.g. "string", "int64", "any"). */
  goType: string;
  /** Python type hint (e.g. "str", "int", "Any"). */
  pyType: string;
  /** Whether this parameter is required. */
  required: boolean;
  /** Where this param lives: path segment, query string, body JSON, or header. */
  location: "path" | "query" | "body" | "header";
}

/** Return type information for a method. */
export interface ReturnType {
  /** Whether this method returns void (204 No Content). */
  isVoid: boolean;
  /** TypeScript type name of the return value (e.g. "Stream", "EventList"). */
  tsType: string;
  /** Go type name (e.g. "*Stream", "[]Member"). */
  goType: string;
  /** Python type hint (e.g. "Stream", "list[Member]"). */
  pyType: string;
  /** Ruby type hint for docs. */
  rbType: string;
  /**
   * If the raw API response wraps the data in an object, this is the key to
   * unwrap (e.g. "streams" for {streams: [...]}). Empty string means no unwrap.
   */
  unwrapKey: string;
  /**
   * When unwrapping, the TS element type inside the array
   * (e.g. "Stream" when unwrapping "streams").
   */
  unwrapElementType?: string;
}

/** A single SDK method (maps to one OpenAPI operation). */
export interface Method {
  /** Method name in the SDK (e.g. "create", "list", "getUser"). */
  name: string;
  /** HTTP method (GET, POST, PATCH, DELETE). */
  httpMethod: string;
  /** URL path template with {param} placeholders (e.g. "/streams/{id}"). */
  pathTemplate: string;
  /** Parameters split by location. */
  pathParams: Param[];
  queryParams: Param[];
  bodyParams: Param[];
  headerParams: Param[];
  /** Return type information. */
  returnType: ReturnType;
  /** Original OpenAPI operationId for traceability. */
  operationId: string;
}

/** A namespace groups related methods (e.g. StreamNamespace). */
export interface Namespace {
  /** Namespace identifier (e.g. "streams", "members", "events"). */
  id: string;
  /** Class name (e.g. "StreamNamespace", "MemberNamespace"). */
  className: string;
  /** Whether this namespace is nested under client.chat. */
  isChat: boolean;
  /** Methods in this namespace. */
  methods: Method[];
}

/** Root-level methods that live on the HeraldAdmin client directly. */
export interface RootMethod extends Method {
  /** Whether this method requires admin auth (vs tenant auth). */
  adminOnly: boolean;
}

/** Complete SDK definition produced by the parser. */
export interface SdkDefinition {
  /** All namespaces. */
  namespaces: Namespace[];
  /** Root-level methods on the client class. */
  rootMethods: RootMethod[];
}
