# Code generated by codegen/generate.ts — DO NOT EDIT.

# frozen_string_literal: true

require "erb"

module HeraldAdmin
  # Groups chat-specific namespaces (conversational layer).
  ChatNamespaces = Struct.new(:presence, :blocks, keyword_init: true)

  class Client
    # Core namespaces (event transport)
    attr_reader :streams, :members, :events, :tenants, :audit

    # @deprecated Use {#chat}.presence instead.
    attr_reader :presence
    # @deprecated Use {#chat}.blocks instead.
    attr_reader :blocks

    # Chat-specific namespaces (conversational layer).
    # Groups presence and block operations that are part of the Herald Chat product.
    attr_reader :chat

    def initialize(url:, token: nil, key: nil, secret: nil, tenant_id: "default")
      transport = HttpTransport.new(url, token: token, key: key, secret: secret)
      @streams = StreamNamespace.new(transport)
      @members = MemberNamespace.new(transport)
      @events = EventNamespace.new(transport)
      @presence = PresenceNamespace.new(transport)
      @tenants = TenantNamespace.new(transport)
      @blocks = BlockNamespace.new(transport)
      @audit = AuditNamespace.new(transport, tenant_id)
      @chat = ChatNamespaces.new(presence: @presence, blocks: @blocks)
      @transport = transport
    end

    def health
      data = @transport.request("GET", "/health")
      HealthResponse.new(
        status: data["status"],
        connections: data["connections"] || 0,
        streams: data["streams"] || 0,
        uptime_secs: data["uptime_secs"] || 0
      )
    end

    def connections
      @transport.request("GET", "/admin/connections")
    end

    def admin_events(limit: nil)
      path = "/admin/events"
      path += "?limit=#{limit}" if limit
      @transport.request("GET", path)
    end

    def errors(limit: nil, category: nil)
      params = []
      params << "limit=#{limit}" if limit
      params << "category=#{ERB::Util.url_encode(category)}" if category
      path = "/admin/errors"
      path += "?#{params.join('&')}" unless params.empty?
      @transport.request("GET", path)
    end

    def stats
      @transport.request("GET", "/admin/stats")
    end
  end
end
