# Code generated by codegen/generate.ts — DO NOT EDIT.

# frozen_string_literal: true

module HeraldAdmin
  class MemberNamespace
    def initialize(transport)
      @t = transport
    end

    def add(stream_id, user_id, role: "member")
      data = @t.request("POST", "/streams/#{esc(stream_id)}/members", { user_id: user_id, role: role })
      Member.new(**data.transform_keys(&:to_sym))
    end

    def list(stream_id)
      data = @t.request("GET", "/streams/#{esc(stream_id)}/members")
      data["members"].map { |m| Member.new(**m.transform_keys(&:to_sym)) }
    end

    def remove(stream_id, user_id)
      @t.request("DELETE", "/streams/#{esc(stream_id)}/members/#{esc(user_id)}")
    end

    def update(stream_id, user_id, role:)
      @t.request("PATCH", "/streams/#{esc(stream_id)}/members/#{esc(user_id)}", { role: role })
    end

    private

    def esc(s) = ERB::Util.url_encode(s)
  end
end
