# Code generated by codegen/generate.ts — DO NOT EDIT.

# frozen_string_literal: true

module HeraldAdmin
  Stream = Struct.new(:id, :name, :meta, :public, :archived, :created_at, keyword_init: true)
  Member = Struct.new(:stream_id, :user_id, :role, :joined_at, keyword_init: true)
  Event = Struct.new(:id, :stream, :seq, :sender, :body, :meta, :parent_id, :edited_at, :sent_at, keyword_init: true)
  EventList = Struct.new(:events, :has_more, keyword_init: true)
  EventPublishResult = Struct.new(:id, :seq, :sent_at, keyword_init: true)
  UserPresence = Struct.new(:user_id, :status, :connections, keyword_init: true)
  MemberPresenceEntry = Struct.new(:user_id, :status, keyword_init: true)
  Cursor = Struct.new(:user_id, :seq, keyword_init: true)
  HealthResponse = Struct.new(:status, :connections, :streams, :uptime_secs, keyword_init: true)
  AuditEvent = Struct.new(:id, :timestamp, :operation, :resource_type, :resource_id, :actor, :result, :tenant_id, :diff, :metadata, keyword_init: true)
  AuditQueryResult = Struct.new(:events, :matched, keyword_init: true)
  AuditCountResult = Struct.new(:count, keyword_init: true)
end
