# Code generated by codegen/generate.ts — DO NOT EDIT.

# frozen_string_literal: true

require_relative "herald_admin/errors"
require_relative "herald_admin/types"
require_relative "herald_admin/transport"
require_relative "herald_admin/streams"
require_relative "herald_admin/members"
require_relative "herald_admin/events"
require_relative "herald_admin/presence"
require_relative "herald_admin/tenants"
require_relative "herald_admin/blocks"
require_relative "herald_admin/audit"
require_relative "herald_admin/client"
