// Code generated by codegen/generate.ts — DO NOT EDIT.

namespace Herald.Admin;

public class HeraldException : Exception
{
    public string Code { get; }
    public int Status { get; }

    public HeraldException(string code, string message, int status)
        : base($"{code}: {message}")
    {
        Code = code;
        Status = status;
    }
}
