// Code generated by codegen/generate.ts — DO NOT EDIT.

using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace Herald.Admin;

internal class HttpTransport
{
    private readonly HttpClient _client;
    private readonly string _baseUrl;

    private static readonly Dictionary<int, string> HttpErrorCodes = new()
    {
        [400] = "BAD_REQUEST", [401] = "UNAUTHORIZED", [403] = "FORBIDDEN",
        [404] = "NOT_FOUND", [409] = "CONFLICT", [429] = "RATE_LIMITED",
        [500] = "INTERNAL", [503] = "UNAVAILABLE",
    };

    public HttpTransport(string baseUrl, string? token = null, string? key = null, string? secret = null)
    {
        _baseUrl = baseUrl.TrimEnd('/');
        _client = new HttpClient();

        if (key != null && secret != null)
        {
            var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{key}:{secret}"));
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", encoded);
        }
        else if (token != null)
        {
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
        }
        else
        {
            throw new ArgumentException("Provide either token or key+secret");
        }
    }

    public async Task<JsonElement?> RequestAsync(string method, string path, object? body = null)
    {
        var url = _baseUrl + path;
        using var request = new HttpRequestMessage(new HttpMethod(method), url);

        if (body != null)
        {
            var json = JsonSerializer.Serialize(body, new JsonSerializerOptions { DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull });
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
        }

        var response = await _client.SendAsync(request);
        var responseBody = await response.Content.ReadAsStringAsync();

        if (!response.IsSuccessStatusCode)
        {
            var code = HttpErrorCodes.GetValueOrDefault((int)response.StatusCode, "INTERNAL");
            var message = $"HTTP {(int)response.StatusCode}";
            if (!string.IsNullOrEmpty(responseBody))
            {
                try
                {
                    var errDoc = JsonDocument.Parse(responseBody);
                    if (errDoc.RootElement.TryGetProperty("error", out var errProp))
                        message = errProp.GetString() ?? message;
                }
                catch
                {
                    message = responseBody;
                }
            }
            throw new HeraldException(code, message, (int)response.StatusCode);
        }

        if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
            return null;

        if (string.IsNullOrEmpty(responseBody))
            return null;

        return JsonDocument.Parse(responseBody).RootElement;
    }
}
