// Code generated by codegen/generate.ts — DO NOT EDIT.

using System.Text.Json;

namespace Herald.Admin;

public static class JsonHelper
{
    public static string GetStr(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetString() ?? "" : "";

    public static int GetInt(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetInt32() : 0;

    public static long GetLong(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetInt64() : 0;

    public static bool GetBool(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) && v.GetBoolean();

    public static long? GetNullableLong(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) && v.ValueKind != JsonValueKind.Null ? v.GetInt64() : null;

    public static JsonElement? GetProp(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v : null;

    /// <summary>Convert a JsonElement to a plain dictionary for contract test validation.</summary>
    public static Dictionary<string, object?> ToDict(JsonElement el)
    {
        var dict = new Dictionary<string, object?>();
        foreach (var prop in el.EnumerateObject())
        {
            dict[prop.Name] = Unwrap(prop.Value);
        }
        return dict;
    }

    public static object? Unwrap(JsonElement el) => el.ValueKind switch
    {
        JsonValueKind.String => el.GetString(),
        JsonValueKind.Number => el.TryGetInt64(out var l) ? (object)l : el.GetDouble(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        JsonValueKind.Null => null,
        JsonValueKind.Array => el.EnumerateArray().Select(Unwrap).ToList(),
        JsonValueKind.Object => ToDict(el),
        _ => null,
    };
}
