<?php
// Code generated by codegen/generate.ts — DO NOT EDIT.

declare(strict_types=1);

// PSR-4 autoloader for Herald\Admin namespace.
spl_autoload_register(function (string $class): void {
    $prefix = 'Herald\\Admin\\';
    if (!str_starts_with($class, $prefix)) return;

    $relative = substr($class, strlen($prefix));
    $file = __DIR__ . '/src/' . str_replace('\\', '/', $relative) . '.php';

    if (file_exists($file)) {
        require_once $file;
    }
});
