// Auth types for Herald's key+secret signed token system.
//
// Connection tokens are HMAC-SHA256 signatures over a canonical payload,
// generated by the tenant's backend server. No JWT, no claims schema.
// See AUTH.md for the full design.
