// C# admin SDK emitter.
// Generates code matching the herald-admin-csharp package structure.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { SdkDefinition } from "../ir.ts";

const HEADER = "// Code generated by codegen/generate.ts — DO NOT EDIT.\n\n";

const ERROR_CS = `${HEADER}namespace Herald.Admin;

public class HeraldException : Exception
{
    public string Code { get; }
    public int Status { get; }

    public HeraldException(string code, string message, int status)
        : base($"{code}: {message}")
    {
        Code = code;
        Status = status;
    }
}
`;

const TRANSPORT_CS = `${HEADER}using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace Herald.Admin;

internal class HttpTransport
{
    private readonly HttpClient _client;
    private readonly string _baseUrl;

    private static readonly Dictionary<int, string> HttpErrorCodes = new()
    {
        [400] = "BAD_REQUEST", [401] = "UNAUTHORIZED", [403] = "FORBIDDEN",
        [404] = "NOT_FOUND", [409] = "CONFLICT", [429] = "RATE_LIMITED",
        [500] = "INTERNAL", [503] = "UNAVAILABLE",
    };

    public HttpTransport(string baseUrl, string? token = null, string? key = null, string? secret = null)
    {
        _baseUrl = baseUrl.TrimEnd('/');
        _client = new HttpClient();

        if (key != null && secret != null)
        {
            var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{key}:{secret}"));
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", encoded);
        }
        else if (token != null)
        {
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
        }
        else
        {
            throw new ArgumentException("Provide either token or key+secret");
        }
    }

    public async Task<JsonElement?> RequestAsync(string method, string path, object? body = null)
    {
        var url = _baseUrl + path;
        using var request = new HttpRequestMessage(new HttpMethod(method), url);

        if (body != null)
        {
            var json = JsonSerializer.Serialize(body, new JsonSerializerOptions { DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull });
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
        }

        var response = await _client.SendAsync(request);
        var responseBody = await response.Content.ReadAsStringAsync();

        if (!response.IsSuccessStatusCode)
        {
            var code = HttpErrorCodes.GetValueOrDefault((int)response.StatusCode, "INTERNAL");
            var message = $"HTTP {(int)response.StatusCode}";
            if (!string.IsNullOrEmpty(responseBody))
            {
                try
                {
                    var errDoc = JsonDocument.Parse(responseBody);
                    if (errDoc.RootElement.TryGetProperty("error", out var errProp))
                        message = errProp.GetString() ?? message;
                }
                catch
                {
                    message = responseBody;
                }
            }
            throw new HeraldException(code, message, (int)response.StatusCode);
        }

        if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
            return null;

        if (string.IsNullOrEmpty(responseBody))
            return null;

        return JsonDocument.Parse(responseBody).RootElement;
    }
}
`;

const TYPES_CS = `${HEADER}using System.Text.Json;

namespace Herald.Admin;

public static class JsonHelper
{
    public static string GetStr(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetString() ?? "" : "";

    public static int GetInt(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetInt32() : 0;

    public static long GetLong(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetInt64() : 0;

    public static bool GetBool(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) && v.GetBoolean();

    public static long? GetNullableLong(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) && v.ValueKind != JsonValueKind.Null ? v.GetInt64() : null;

    public static JsonElement? GetProp(JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v : null;

    /// <summary>Convert a JsonElement to a plain dictionary for contract test validation.</summary>
    public static Dictionary<string, object?> ToDict(JsonElement el)
    {
        var dict = new Dictionary<string, object?>();
        foreach (var prop in el.EnumerateObject())
        {
            dict[prop.Name] = Unwrap(prop.Value);
        }
        return dict;
    }

    public static object? Unwrap(JsonElement el) => el.ValueKind switch
    {
        JsonValueKind.String => el.GetString(),
        JsonValueKind.Number => el.TryGetInt64(out var l) ? (object)l : el.GetDouble(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        JsonValueKind.Null => null,
        JsonValueKind.Array => el.EnumerateArray().Select(Unwrap).ToList(),
        JsonValueKind.Object => ToDict(el),
        _ => null,
    };
}
`;

const CLIENT_CS = `${HEADER}using System.Text.Json;
using System.Web;

namespace Herald.Admin;

public class ChatNamespaces
{
    public PresenceNamespace Presence { get; }
    public BlockNamespace Blocks { get; }

    internal ChatNamespaces(PresenceNamespace presence, BlockNamespace blocks)
    {
        Presence = presence;
        Blocks = blocks;
    }
}

public class HeraldAdmin
{
    public StreamNamespace Streams { get; }
    public MemberNamespace Members { get; }
    public EventNamespace Events { get; }
    public TenantNamespace Tenants { get; }
    public AuditNamespace? Audit { get; }
    public ChatNamespaces Chat { get; }
    private readonly HttpTransport _transport;

    public HeraldAdmin(string url, string? token = null, string? key = null, string? secret = null, string? tenantId = null)
    {
        _transport = new HttpTransport(url, token, key, secret);
        Streams = new StreamNamespace(_transport);
        Members = new MemberNamespace(_transport);
        Events = new EventNamespace(_transport);
        Tenants = new TenantNamespace(_transport);
        var presence = new PresenceNamespace(_transport);
        var blocks = new BlockNamespace(_transport);
        Chat = new ChatNamespaces(presence, blocks);
        Audit = tenantId != null ? new AuditNamespace(_transport, tenantId) : null;
    }

    public async Task<JsonElement?> HealthAsync() =>
        await _transport.RequestAsync("GET", "/health");

    public async Task<JsonElement?> ConnectionsAsync() =>
        await _transport.RequestAsync("GET", "/admin/connections");

    public async Task<JsonElement?> AdminEventsAsync(int? limit = null)
    {
        var path = "/admin/events";
        if (limit.HasValue) path += $"?limit={limit.Value}";
        return await _transport.RequestAsync("GET", path);
    }

    public async Task<JsonElement?> ErrorsAsync(int? limit = null, string? category = null)
    {
        var parts = new List<string>();
        if (limit.HasValue) parts.Add($"limit={limit.Value}");
        if (category != null) parts.Add($"category={Uri.EscapeDataString(category)}");
        var path = "/admin/errors";
        if (parts.Count > 0) path += "?" + string.Join("&", parts);
        return await _transport.RequestAsync("GET", path);
    }

    public async Task<JsonElement?> StatsAsync() =>
        await _transport.RequestAsync("GET", "/admin/stats");
}

public class StreamNamespace
{
    private readonly HttpTransport _t;
    internal StreamNamespace(HttpTransport t) => _t = t;

    public async Task<JsonElement?> CreateAsync(string id, string name, object? meta = null, bool @public = false)
    {
        var body = new Dictionary<string, object?> { ["id"] = id, ["name"] = name };
        if (meta != null) body["meta"] = meta;
        if (@public) body["public"] = true;
        return await _t.RequestAsync("POST", "/streams", body);
    }

    public async Task<JsonElement?> GetAsync(string id) =>
        await _t.RequestAsync("GET", $"/streams/{Uri.EscapeDataString(id)}");

    public async Task UpdateAsync(string id, string? name = null, object? meta = null, bool? archived = null)
    {
        var body = new Dictionary<string, object?>();
        if (name != null) body["name"] = name;
        if (meta != null) body["meta"] = meta;
        if (archived.HasValue) body["archived"] = archived.Value;
        await _t.RequestAsync("PATCH", $"/streams/{Uri.EscapeDataString(id)}", body);
    }

    public async Task<List<Dictionary<string, object?>>> ListAsync()
    {
        var data = await _t.RequestAsync("GET", "/streams");
        return data!.Value.GetProperty("streams").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }

    public async Task DeleteAsync(string id) =>
        await _t.RequestAsync("DELETE", $"/streams/{Uri.EscapeDataString(id)}");
}

public class MemberNamespace
{
    private readonly HttpTransport _t;
    internal MemberNamespace(HttpTransport t) => _t = t;

    public async Task<JsonElement?> AddAsync(string streamId, string userId, string role = "member") =>
        await _t.RequestAsync("POST", $"/streams/{Uri.EscapeDataString(streamId)}/members",
            new Dictionary<string, object?> { ["user_id"] = userId, ["role"] = role });

    public async Task<List<Dictionary<string, object?>>> ListAsync(string streamId)
    {
        var data = await _t.RequestAsync("GET", $"/streams/{Uri.EscapeDataString(streamId)}/members");
        return data!.Value.GetProperty("members").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }

    public async Task RemoveAsync(string streamId, string userId) =>
        await _t.RequestAsync("DELETE", $"/streams/{Uri.EscapeDataString(streamId)}/members/{Uri.EscapeDataString(userId)}");

    public async Task UpdateAsync(string streamId, string userId, string role) =>
        await _t.RequestAsync("PATCH", $"/streams/{Uri.EscapeDataString(streamId)}/members/{Uri.EscapeDataString(userId)}",
            new Dictionary<string, object?> { ["role"] = role });
}

public class EventNamespace
{
    private readonly HttpTransport _t;
    internal EventNamespace(HttpTransport t) => _t = t;

    public async Task<JsonElement?> PublishAsync(string streamId, string sender, string body, object? meta = null, string? parentId = null)
    {
        var req = new Dictionary<string, object?> { ["sender"] = sender, ["body"] = body };
        if (meta != null) req["meta"] = meta;
        if (parentId != null) req["parent_id"] = parentId;
        return await _t.RequestAsync("POST", $"/streams/{Uri.EscapeDataString(streamId)}/events", req);
    }

    public async Task<Dictionary<string, object?>> ListAsync(string streamId, long? before = null, long? after = null, int? limit = null, string? thread = null)
    {
        var parts = new List<string>();
        if (before.HasValue) parts.Add($"before={before.Value}");
        if (after.HasValue) parts.Add($"after={after.Value}");
        if (limit.HasValue) parts.Add($"limit={limit.Value}");
        if (thread != null) parts.Add($"thread={Uri.EscapeDataString(thread)}");
        var qs = parts.Count > 0 ? "?" + string.Join("&", parts) : "";
        var data = await _t.RequestAsync("GET", $"/streams/{Uri.EscapeDataString(streamId)}/events{qs}");
        return JsonHelper.ToDict(data!.Value);
    }

    public async Task DeleteAsync(string streamId, string eventId) =>
        await _t.RequestAsync("DELETE", $"/streams/{Uri.EscapeDataString(streamId)}/events/{Uri.EscapeDataString(eventId)}");

    public async Task EditAsync(string streamId, string eventId, string body) =>
        await _t.RequestAsync("PATCH", $"/streams/{Uri.EscapeDataString(streamId)}/events/{Uri.EscapeDataString(eventId)}",
            new Dictionary<string, object?> { ["body"] = body });

    public async Task<List<Dictionary<string, object?>>> GetReactionsAsync(string streamId, string eventId)
    {
        var data = await _t.RequestAsync("GET", $"/streams/{Uri.EscapeDataString(streamId)}/events/{Uri.EscapeDataString(eventId)}/reactions");
        return data!.Value.GetProperty("reactions").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }

    public async Task TriggerAsync(string streamId, string @event, object? data = null)
    {
        var body = new Dictionary<string, object?> { ["event"] = @event };
        if (data != null) body["data"] = data;
        await _t.RequestAsync("POST", $"/streams/{Uri.EscapeDataString(streamId)}/trigger", body);
    }
}

public class PresenceNamespace
{
    private readonly HttpTransport _t;
    internal PresenceNamespace(HttpTransport t) => _t = t;

    public async Task<Dictionary<string, object?>> GetUserAsync(string userId)
    {
        var data = await _t.RequestAsync("GET", $"/presence/{Uri.EscapeDataString(userId)}");
        return JsonHelper.ToDict(data!.Value);
    }

    public async Task<List<Dictionary<string, object?>>> GetStreamAsync(string streamId)
    {
        var data = await _t.RequestAsync("GET", $"/streams/{Uri.EscapeDataString(streamId)}/presence");
        return data!.Value.GetProperty("members").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }

    public async Task<List<Dictionary<string, object?>>> GetCursorsAsync(string streamId)
    {
        var data = await _t.RequestAsync("GET", $"/streams/{Uri.EscapeDataString(streamId)}/cursors");
        return data!.Value.GetProperty("cursors").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }
}

public class BlockNamespace
{
    private readonly HttpTransport _t;
    internal BlockNamespace(HttpTransport t) => _t = t;

    public async Task BlockAsync(string userId, string blockedId) =>
        await _t.RequestAsync("POST", "/blocks", new Dictionary<string, object?> { ["user_id"] = userId, ["blocked_id"] = blockedId });

    public async Task UnblockAsync(string userId, string blockedId) =>
        await _t.RequestAsync("DELETE", "/blocks", new Dictionary<string, object?> { ["user_id"] = userId, ["blocked_id"] = blockedId });

    public async Task<List<object?>> ListAsync(string userId)
    {
        var data = await _t.RequestAsync("GET", $"/blocks/{Uri.EscapeDataString(userId)}");
        return data!.Value.GetProperty("blocked").EnumerateArray().Select(x => (object?)x.GetString()).ToList();
    }
}

public class TenantNamespace
{
    private readonly HttpTransport _t;
    internal TenantNamespace(HttpTransport t) => _t = t;

    public async Task<JsonElement?> CreateAsync(string name, string? plan = null)
    {
        var body = new Dictionary<string, object?> { ["name"] = name };
        if (plan != null) body["plan"] = plan;
        return await _t.RequestAsync("POST", "/admin/tenants", body);
    }

    public async Task<List<Dictionary<string, object?>>> ListAsync()
    {
        var data = await _t.RequestAsync("GET", "/admin/tenants");
        return data!.Value.GetProperty("tenants").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }

    public async Task<JsonElement?> GetAsync(string id) =>
        await _t.RequestAsync("GET", $"/admin/tenants/{Uri.EscapeDataString(id)}");

    public async Task UpdateAsync(string id, string? name = null, string? plan = null, int? eventTtlDays = null)
    {
        var body = new Dictionary<string, object?>();
        if (name != null) body["name"] = name;
        if (plan != null) body["plan"] = plan;
        if (eventTtlDays.HasValue) body["event_ttl_days"] = eventTtlDays.Value;
        await _t.RequestAsync("PATCH", $"/admin/tenants/{Uri.EscapeDataString(id)}", body);
    }

    public async Task DeleteAsync(string id) =>
        await _t.RequestAsync("DELETE", $"/admin/tenants/{Uri.EscapeDataString(id)}");

    public async Task<string> CreateTokenAsync(string tenantId, string? scope = null)
    {
        var body = scope != null ? new Dictionary<string, object?> { ["scope"] = scope } : null;
        var data = await _t.RequestAsync("POST", $"/admin/tenants/{Uri.EscapeDataString(tenantId)}/tokens", body);
        return data!.Value.GetProperty("token").GetString()!;
    }

    public async Task DeleteTokenAsync(string tenantId, string token) =>
        await _t.RequestAsync("DELETE", $"/admin/tenants/{Uri.EscapeDataString(tenantId)}/tokens/{Uri.EscapeDataString(token)}");

    public async Task<List<string>> ListTokensAsync(string tenantId)
    {
        var data = await _t.RequestAsync("GET", $"/admin/tenants/{Uri.EscapeDataString(tenantId)}/tokens");
        return data!.Value.GetProperty("tokens").EnumerateArray().Select(x => x.GetString()!).ToList();
    }

    public async Task<List<Dictionary<string, object?>>> ListStreamsAsync(string tenantId)
    {
        var data = await _t.RequestAsync("GET", $"/admin/tenants/{Uri.EscapeDataString(tenantId)}/streams");
        return data!.Value.GetProperty("streams").EnumerateArray().Select(JsonHelper.ToDict).ToList();
    }
}

public class AuditNamespace
{
    private readonly HttpTransport _t;
    private readonly string _tenantId;

    internal AuditNamespace(HttpTransport t, string tenantId)
    {
        _t = t;
        _tenantId = tenantId;
    }

    public async Task<JsonElement?> QueryAsync(string? operation = null, string? resourceType = null, string? resourceId = null, string? actor = null, string? result = null, string? since = null, string? until = null, int? limit = null)
    {
        var parts = BuildParams(operation, resourceType, resourceId, actor, result, since, until);
        if (limit.HasValue) parts.Add($"limit={limit.Value}");
        var path = BasePath();
        if (parts.Count > 0) path += "?" + string.Join("&", parts);
        return await _t.RequestAsync("GET", path);
    }

    public async Task<int> CountAsync(string? operation = null, string? resourceType = null, string? resourceId = null, string? actor = null, string? result = null, string? since = null, string? until = null)
    {
        var parts = BuildParams(operation, resourceType, resourceId, actor, result, since, until);
        var path = BasePath() + "/count";
        if (parts.Count > 0) path += "?" + string.Join("&", parts);
        var data = await _t.RequestAsync("GET", path);
        return data!.Value.GetProperty("count").GetInt32();
    }

    private string BasePath() => $"/admin/tenants/{Uri.EscapeDataString(_tenantId)}/audit";

    private static List<string> BuildParams(string? op, string? rt, string? ri, string? actor, string? result, string? since, string? until)
    {
        var parts = new List<string>();
        if (op != null) parts.Add($"operation={Uri.EscapeDataString(op)}");
        if (rt != null) parts.Add($"resource_type={Uri.EscapeDataString(rt)}");
        if (ri != null) parts.Add($"resource_id={Uri.EscapeDataString(ri)}");
        if (actor != null) parts.Add($"actor={Uri.EscapeDataString(actor)}");
        if (result != null) parts.Add($"result={Uri.EscapeDataString(result)}");
        if (since != null) parts.Add($"since={Uri.EscapeDataString(since)}");
        if (until != null) parts.Add($"until={Uri.EscapeDataString(until)}");
        return parts;
    }
}
`;

export function emitCsharp(sdk: SdkDefinition, outDir: string): void {
  mkdirSync(outDir, { recursive: true });

  writeFileSync(join(outDir, "HeraldException.cs"), ERROR_CS);
  writeFileSync(join(outDir, "HttpTransport.cs"), TRANSPORT_CS);
  writeFileSync(join(outDir, "Types.cs"), TYPES_CS);
  writeFileSync(join(outDir, "HeraldAdmin.cs"), CLIENT_CS);

  console.log(`  C#: wrote 4 files to ${outDir}`);
}
