// PHP admin SDK emitter.
// Generates code matching the herald-admin-php package structure.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { SdkDefinition } from "../ir.ts";

const HEADER = "<?php\n// Code generated by codegen/generate.ts — DO NOT EDIT.\n\n";

const ERROR_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin;

class HeraldError extends \\RuntimeException
{
    public readonly string \$code;
    public readonly int \$status;

    public function __construct(string \$code, string \$message, int \$status = 0)
    {
        parent::__construct("{$code}: {$message}");
        \$this->code = \$code;
        \$this->status = \$status;
    }
}
`;

const TRANSPORT_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin;

class HttpTransport
{
    private string \$baseUrl;
    private string \$authHeader;
    private int \$timeoutSecs;

    private const HTTP_ERROR_CODES = [
        400 => 'BAD_REQUEST', 401 => 'UNAUTHORIZED', 403 => 'FORBIDDEN',
        404 => 'NOT_FOUND', 409 => 'CONFLICT', 429 => 'RATE_LIMITED',
        500 => 'INTERNAL', 503 => 'UNAVAILABLE',
    ];

    public function __construct(string \$baseUrl, ?string \$token = null, ?string \$key = null, ?string \$secret = null, int \$timeoutSecs = 30)
    {
        \$this->baseUrl = rtrim(\$baseUrl, '/');
        if (\$key !== null && \$secret !== null) {
            \$this->authHeader = 'Basic ' . base64_encode("{$key}:{$secret}");
        } elseif (\$token !== null) {
            \$this->authHeader = "Bearer {$token}";
        } else {
            throw new \\InvalidArgumentException('Provide either token or key+secret');
        }
        \$this->timeoutSecs = \$timeoutSecs;
    }

    /**
     * @return mixed
     */
    public function request(string \$method, string \$path, mixed \$body = null): mixed
    {
        \$url = \$this->baseUrl . \$path;
        \$headers = ["Authorization: {\$this->authHeader}"];
        \$payload = null;

        if (\$body !== null) {
            \$payload = json_encode(\$body, JSON_THROW_ON_ERROR);
            \$headers[] = 'Content-Type: application/json';
        }

        \$opts = [
            'http' => [
                'method' => strtoupper(\$method),
                'header' => implode("\\r\\n", \$headers),
                'timeout' => \$this->timeoutSecs,
                'ignore_errors' => true,
            ],
        ];
        if (\$payload !== null) {
            \$opts['http']['content'] = \$payload;
        }

        \$context = stream_context_create(\$opts);
        \$raw = @file_get_contents(\$url, false, \$context);

        // Parse status code from response headers
        \$statusCode = 0;
        \$responseHeaders = function_exists('http_get_last_response_headers')
            ? (http_get_last_response_headers() ?? [])
            : (\$http_response_header ?? []);
        foreach (\$responseHeaders as \$hdr) {
            if (preg_match('/^HTTP\\/[\\d.]+ (\\d+)/', \$hdr, \$m)) {
                \$statusCode = (int)\$m[1];
            }
        }

        if (\$raw === false && \$statusCode === 0) {
            throw new HeraldError('INTERNAL', 'Request failed: unable to connect');
        }

        if (\$statusCode >= 400) {
            \$code = self::HTTP_ERROR_CODES[\$statusCode] ?? 'INTERNAL';
            \$message = "HTTP {\$statusCode}";
            if (\$raw) {
                \$data = json_decode(\$raw, true);
                if (is_array(\$data) && isset(\$data['error'])) {
                    \$message = \$data['error'];
                } elseif (\$raw !== '') {
                    \$message = \$raw;
                }
            }
            throw new HeraldError(\$code, \$message, \$statusCode);
        }

        if (\$statusCode === 204) {
            return null;
        }

        if (\$raw === '' || \$raw === false) {
            return null;
        }

        return json_decode(\$raw, true, 512, JSON_THROW_ON_ERROR);
    }
}
`;

const STREAMS_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class StreamNamespace
{
    public function __construct(private readonly HttpTransport \$t) {}

    public function create(string \$id, string \$name, mixed \$meta = null, bool \$public = false): array
    {
        \$body = ['id' => \$id, 'name' => \$name];
        if (\$meta !== null) \$body['meta'] = \$meta;
        if (\$public) \$body['public'] = true;
        return \$this->t->request('POST', '/streams', \$body);
    }

    public function get(string \$id): array
    {
        return \$this->t->request('GET', '/streams/' . rawurlencode(\$id));
    }

    public function update(string \$id, ?string \$name = null, mixed \$meta = null, ?bool \$archived = null): void
    {
        \$body = [];
        if (\$name !== null) \$body['name'] = \$name;
        if (\$meta !== null) \$body['meta'] = \$meta;
        if (\$archived !== null) \$body['archived'] = \$archived;
        \$this->t->request('PATCH', '/streams/' . rawurlencode(\$id), \$body);
    }

    public function list(): array
    {
        \$data = \$this->t->request('GET', '/streams');
        return \$data['streams'];
    }

    public function delete(string \$id): void
    {
        \$this->t->request('DELETE', '/streams/' . rawurlencode(\$id));
    }
}
`;

const MEMBERS_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class MemberNamespace
{
    public function __construct(private readonly HttpTransport \$t) {}

    public function add(string \$streamId, string \$userId, string \$role = 'member'): array
    {
        return \$this->t->request('POST', '/streams/' . rawurlencode(\$streamId) . '/members', ['user_id' => \$userId, 'role' => \$role]);
    }

    public function list(string \$streamId): array
    {
        \$data = \$this->t->request('GET', '/streams/' . rawurlencode(\$streamId) . '/members');
        return \$data['members'];
    }

    public function remove(string \$streamId, string \$userId): void
    {
        \$this->t->request('DELETE', '/streams/' . rawurlencode(\$streamId) . '/members/' . rawurlencode(\$userId));
    }

    public function update(string \$streamId, string \$userId, string \$role): void
    {
        \$this->t->request('PATCH', '/streams/' . rawurlencode(\$streamId) . '/members/' . rawurlencode(\$userId), ['role' => \$role]);
    }
}
`;

const EVENTS_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class EventNamespace
{
    public function __construct(private readonly HttpTransport \$t) {}

    public function publish(string \$streamId, string \$sender, string \$body, mixed \$meta = null, ?string \$parentId = null, ?string \$excludeConnection = null): array
    {
        \$req = ['sender' => \$sender, 'body' => \$body];
        if (\$meta !== null) \$req['meta'] = \$meta;
        if (\$parentId !== null) \$req['parent_id'] = \$parentId;
        if (\$excludeConnection !== null) \$req['exclude_connection'] = \$excludeConnection;
        return \$this->t->request('POST', '/streams/' . rawurlencode(\$streamId) . '/events', \$req);
    }

    public function list(string \$streamId, ?int \$before = null, ?int \$after = null, ?int \$limit = null, ?string \$thread = null): array
    {
        \$params = [];
        if (\$before !== null) \$params[] = "before={\$before}";
        if (\$after !== null) \$params[] = "after={\$after}";
        if (\$limit !== null) \$params[] = "limit={\$limit}";
        if (\$thread !== null) \$params[] = 'thread=' . rawurlencode(\$thread);
        \$qs = \$params ? '?' . implode('&', \$params) : '';
        return \$this->t->request('GET', '/streams/' . rawurlencode(\$streamId) . "/events{\$qs}");
    }

    public function delete(string \$streamId, string \$eventId): void
    {
        \$this->t->request('DELETE', '/streams/' . rawurlencode(\$streamId) . '/events/' . rawurlencode(\$eventId));
    }

    public function edit(string \$streamId, string \$eventId, string \$body): void
    {
        \$this->t->request('PATCH', '/streams/' . rawurlencode(\$streamId) . '/events/' . rawurlencode(\$eventId), ['body' => \$body]);
    }

    public function getReactions(string \$streamId, string \$eventId): array
    {
        \$data = \$this->t->request('GET', '/streams/' . rawurlencode(\$streamId) . '/events/' . rawurlencode(\$eventId) . '/reactions');
        return \$data['reactions'];
    }

    public function trigger(string \$streamId, string \$event, mixed \$data = null, ?int \$excludeConnection = null): void
    {
        \$body = ['event' => \$event];
        if (\$data !== null) \$body['data'] = \$data;
        if (\$excludeConnection !== null) \$body['exclude_connection'] = \$excludeConnection;
        \$this->t->request('POST', '/streams/' . rawurlencode(\$streamId) . '/trigger', \$body);
    }
}
`;

const PRESENCE_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class PresenceNamespace
{
    public function __construct(private readonly HttpTransport \$t) {}

    public function getUser(string \$userId): array
    {
        return \$this->t->request('GET', '/presence/' . rawurlencode(\$userId));
    }

    public function getStream(string \$streamId): array
    {
        \$data = \$this->t->request('GET', '/streams/' . rawurlencode(\$streamId) . '/presence');
        return \$data['members'];
    }

    public function getCursors(string \$streamId): array
    {
        \$data = \$this->t->request('GET', '/streams/' . rawurlencode(\$streamId) . '/cursors');
        return \$data['cursors'];
    }

    public function getBulk(array \$userIds): array
    {
        \$ids = implode(',', array_map('urlencode', \$userIds));
        \$data = \$this->t->request('GET', "/presence?user_ids={\$ids}");
        return \$data['users'];
    }

    public function setOverride(string \$userId, array \$options): array
    {
        return \$this->t->request('POST', '/presence/' . urlencode(\$userId), \$options);
    }
}
`;

const BLOCKS_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class BlockNamespace
{
    public function __construct(private readonly HttpTransport \$t) {}

    public function block(string \$userId, string \$blockedId): void
    {
        \$this->t->request('POST', '/blocks', ['user_id' => \$userId, 'blocked_id' => \$blockedId]);
    }

    public function unblock(string \$userId, string \$blockedId): void
    {
        \$this->t->request('DELETE', '/blocks', ['user_id' => \$userId, 'blocked_id' => \$blockedId]);
    }

    public function list(string \$userId): array
    {
        \$data = \$this->t->request('GET', '/blocks/' . rawurlencode(\$userId));
        return \$data['blocked'];
    }
}
`;

const TENANTS_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class TenantNamespace
{
    public function __construct(private readonly HttpTransport \$t) {}

    public function create(string \$name, ?string \$plan = null): array
    {
        \$body = ['name' => \$name];
        if (\$plan !== null) \$body['plan'] = \$plan;
        return \$this->t->request('POST', '/admin/tenants', \$body);
    }

    public function list(): array
    {
        \$data = \$this->t->request('GET', '/admin/tenants');
        return \$data['tenants'];
    }

    public function get(string \$id): array
    {
        return \$this->t->request('GET', '/admin/tenants/' . rawurlencode(\$id));
    }

    public function update(string \$id, ?string \$name = null, ?string \$plan = null, ?int \$eventTtlDays = null): void
    {
        \$body = [];
        if (\$name !== null) \$body['name'] = \$name;
        if (\$plan !== null) \$body['plan'] = \$plan;
        if (\$eventTtlDays !== null) \$body['event_ttl_days'] = \$eventTtlDays;
        \$this->t->request('PATCH', '/admin/tenants/' . rawurlencode(\$id), \$body);
    }

    public function delete(string \$id): void
    {
        \$this->t->request('DELETE', '/admin/tenants/' . rawurlencode(\$id));
    }

    public function createToken(string \$tenantId, ?string \$scope = null): string
    {
        \$body = \$scope !== null ? ['scope' => \$scope] : null;
        \$data = \$this->t->request('POST', '/admin/tenants/' . rawurlencode(\$tenantId) . '/tokens', \$body);
        return \$data['token'];
    }

    public function deleteToken(string \$tenantId, string \$token): void
    {
        \$this->t->request('DELETE', '/admin/tenants/' . rawurlencode(\$tenantId) . '/tokens/' . rawurlencode(\$token));
    }

    public function listTokens(string \$tenantId): array
    {
        \$data = \$this->t->request('GET', '/admin/tenants/' . rawurlencode(\$tenantId) . '/tokens');
        return \$data['tokens'];
    }

    public function listStreams(string \$tenantId): array
    {
        \$data = \$this->t->request('GET', '/admin/tenants/' . rawurlencode(\$tenantId) . '/streams');
        return \$data['streams'];
    }

    public function purgeData(string \$tenantId): array
    {
        return \$this->t->request('DELETE', '/admin/tenants/' . rawurlencode(\$tenantId) . '/data');
    }
}
`;

const AUDIT_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin\\Namespaces;

use Herald\\Admin\\HttpTransport;

class AuditNamespace
{
    public function __construct(
        private readonly HttpTransport \$t,
        private readonly string \$tenantId,
    ) {}

    public function query(
        ?string \$operation = null,
        ?string \$resourceType = null,
        ?string \$resourceId = null,
        ?string \$actor = null,
        ?string \$result = null,
        ?string \$since = null,
        ?string \$until = null,
        ?int \$limit = null,
    ): array {
        \$params = \$this->buildParams(\$operation, \$resourceType, \$resourceId, \$actor, \$result, \$since, \$until);
        if (\$limit !== null) \$params[] = "limit={\$limit}";
        \$path = \$this->basePath();
        if (\$params) \$path .= '?' . implode('&', \$params);
        return \$this->t->request('GET', \$path);
    }

    public function count(
        ?string \$operation = null,
        ?string \$resourceType = null,
        ?string \$resourceId = null,
        ?string \$actor = null,
        ?string \$result = null,
        ?string \$since = null,
        ?string \$until = null,
    ): int {
        \$params = \$this->buildParams(\$operation, \$resourceType, \$resourceId, \$actor, \$result, \$since, \$until);
        \$path = \$this->basePath() . '/count';
        if (\$params) \$path .= '?' . implode('&', \$params);
        \$data = \$this->t->request('GET', \$path);
        return \$data['count'];
    }

    private function basePath(): string
    {
        return '/admin/tenants/' . rawurlencode(\$this->tenantId) . '/audit';
    }

    /**
     * @return string[]
     */
    private function buildParams(?string \$op, ?string \$rt, ?string \$ri, ?string \$actor, ?string \$result, ?string \$since, ?string \$until): array
    {
        \$params = [];
        if (\$op !== null) \$params[] = 'operation=' . rawurlencode(\$op);
        if (\$rt !== null) \$params[] = 'resource_type=' . rawurlencode(\$rt);
        if (\$ri !== null) \$params[] = 'resource_id=' . rawurlencode(\$ri);
        if (\$actor !== null) \$params[] = 'actor=' . rawurlencode(\$actor);
        if (\$result !== null) \$params[] = 'result=' . rawurlencode(\$result);
        if (\$since !== null) \$params[] = 'since=' . rawurlencode(\$since);
        if (\$until !== null) \$params[] = 'until=' . rawurlencode(\$until);
        return \$params;
    }
}
`;

const CLIENT_PHP = `${HEADER}declare(strict_types=1);

namespace Herald\\Admin;

use Herald\\Admin\\Namespaces\\StreamNamespace;
use Herald\\Admin\\Namespaces\\MemberNamespace;
use Herald\\Admin\\Namespaces\\EventNamespace;
use Herald\\Admin\\Namespaces\\PresenceNamespace;
use Herald\\Admin\\Namespaces\\TenantNamespace;
use Herald\\Admin\\Namespaces\\AuditNamespace;
use Herald\\Admin\\Namespaces\\BlockNamespace;

class ChatNamespaces
{
    public function __construct(
        public readonly BlockNamespace \$blocks,
    ) {}
}

class HeraldAdmin
{
    public readonly StreamNamespace \$streams;
    public readonly MemberNamespace \$members;
    public readonly EventNamespace \$events;
    public readonly TenantNamespace \$tenants;
    public readonly ?AuditNamespace \$audit;
    public readonly PresenceNamespace \$presence;
    public readonly ChatNamespaces \$chat;
    private readonly HttpTransport \$transport;

    public function __construct(
        string \$url,
        ?string \$token = null,
        ?string \$key = null,
        ?string \$secret = null,
        ?string \$tenantId = null,
    ) {
        \$this->transport = new HttpTransport(\$url, \$token, \$key, \$secret);
        \$this->streams = new StreamNamespace(\$this->transport);
        \$this->members = new MemberNamespace(\$this->transport);
        \$this->events = new EventNamespace(\$this->transport);
        \$this->tenants = new TenantNamespace(\$this->transport);
        \$this->presence = new PresenceNamespace(\$this->transport);
        \$this->chat = new ChatNamespaces(new BlockNamespace(\$this->transport));
        \$this->audit = \$tenantId !== null ? new AuditNamespace(\$this->transport, \$tenantId) : null;
    }

    public function health(): array
    {
        return \$this->transport->request('GET', '/health');
    }

    public function connections(): array
    {
        return \$this->transport->request('GET', '/admin/connections');
    }

    public function adminEvents(?int \$limit = null): array
    {
        \$path = '/admin/events';
        if (\$limit !== null) \$path .= "?limit={\$limit}";
        return \$this->transport->request('GET', \$path);
    }

    public function errors(?int \$limit = null, ?string \$category = null): array
    {
        \$params = [];
        if (\$limit !== null) \$params[] = "limit={\$limit}";
        if (\$category !== null) \$params[] = 'category=' . rawurlencode(\$category);
        \$path = '/admin/errors';
        if (\$params) \$path .= '?' . implode('&', \$params);
        return \$this->transport->request('GET', \$path);
    }

    public function stats(): array
    {
        return \$this->transport->request('GET', '/admin/stats');
    }
}
`;

const AUTOLOAD_PHP = `${HEADER}declare(strict_types=1);

// PSR-4 autoloader for Herald\\Admin namespace.
spl_autoload_register(function (string \$class): void {
    \$prefix = 'Herald\\\\Admin\\\\';
    if (!str_starts_with(\$class, \$prefix)) return;

    \$relative = substr(\$class, strlen(\$prefix));
    \$file = __DIR__ . '/src/' . str_replace('\\\\', '/', \$relative) . '.php';

    if (file_exists(\$file)) {
        require_once \$file;
    }
});
`;

export function emitPhp(sdk: SdkDefinition, outDir: string): void {
  const srcDir = join(outDir, "src");
  const nsDir = join(srcDir, "Namespaces");
  mkdirSync(nsDir, { recursive: true });

  writeFileSync(join(outDir, "autoload.php"), AUTOLOAD_PHP);
  writeFileSync(join(srcDir, "HeraldError.php"), ERROR_PHP);
  writeFileSync(join(srcDir, "HttpTransport.php"), TRANSPORT_PHP);
  writeFileSync(join(srcDir, "HeraldAdmin.php"), CLIENT_PHP);
  writeFileSync(join(nsDir, "StreamNamespace.php"), STREAMS_PHP);
  writeFileSync(join(nsDir, "MemberNamespace.php"), MEMBERS_PHP);
  writeFileSync(join(nsDir, "EventNamespace.php"), EVENTS_PHP);
  writeFileSync(join(nsDir, "PresenceNamespace.php"), PRESENCE_PHP);
  writeFileSync(join(nsDir, "TenantNamespace.php"), TENANTS_PHP);
  writeFileSync(join(nsDir, "AuditNamespace.php"), AUDIT_PHP);
  writeFileSync(join(nsDir, "BlockNamespace.php"), BLOCKS_PHP);

  console.log(`  PHP: wrote 11 files to ${outDir}`);
}
