// Ruby admin SDK emitter.
// Generates code matching the herald-admin-ruby package structure.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { SdkDefinition } from "../ir.ts";

const HEADER = "# Code generated by codegen/generate.ts — DO NOT EDIT.\n\n";

const ERRORS_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  class HeraldError < StandardError
    attr_reader :code, :status

    def initialize(code, message, status: 0)
      super("\#{code}: \#{message}")
      @code = code
      @status = status
    end
  end
end
`;

const TYPES_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  Stream = Struct.new(:id, :name, :meta, :public, :archived, :created_at, keyword_init: true)
  Member = Struct.new(:stream_id, :user_id, :role, :joined_at, keyword_init: true)
  Event = Struct.new(:id, :stream, :seq, :sender, :body, :meta, :parent_id, :edited_at, :sent_at, keyword_init: true)
  EventList = Struct.new(:events, :has_more, keyword_init: true)
  EventPublishResult = Struct.new(:id, :seq, :sent_at, keyword_init: true)
  UserPresence = Struct.new(:user_id, :status, :connections, keyword_init: true)
  MemberPresenceEntry = Struct.new(:user_id, :status, keyword_init: true)
  Cursor = Struct.new(:user_id, :seq, keyword_init: true)
  HealthResponse = Struct.new(:status, :connections, :streams, :uptime_secs, keyword_init: true)
  AuditEvent = Struct.new(:id, :timestamp, :operation, :resource_type, :resource_id, :actor, :result, :tenant_id, :diff, :metadata, keyword_init: true)
  AuditQueryResult = Struct.new(:events, :matched, keyword_init: true)
  AuditCountResult = Struct.new(:count, keyword_init: true)
end
`;

const TRANSPORT_RB = `${HEADER}# frozen_string_literal: true

require "net/http"
require "json"
require "uri"

module HeraldAdmin
  class HttpTransport
    def initialize(base_url, token: nil, key: nil, secret: nil)
      @base_url = base_url.chomp("/")
      @auth_header = if key && secret
                       "Basic \#{["\#{key}:\#{secret}"].pack("m0")}"
                     elsif token
                       "Bearer \#{token}"
                     else
                       raise ArgumentError, "provide either token or key+secret"
                     end
    end

    def request(method, path, body = nil)
      uri = URI("\#{@base_url}\#{path}")
      req = case method.upcase
            when "GET"    then Net::HTTP::Get.new(uri)
            when "POST"   then Net::HTTP::Post.new(uri)
            when "PATCH"  then Net::HTTP::Patch.new(uri)
            when "DELETE" then Net::HTTP::Delete.new(uri)
            else raise ArgumentError, "unknown method: \#{method}"
            end

      req["Authorization"] = @auth_header
      if body
        req["Content-Type"] = "application/json"
        req.body = JSON.generate(body)
      end

      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == "https"
      http.open_timeout = 10
      http.read_timeout = 30
      resp = http.request(req)

      status = resp.code.to_i
      if status >= 400
        http_codes = {
          400 => "BAD_REQUEST", 401 => "UNAUTHORIZED", 403 => "FORBIDDEN",
          404 => "NOT_FOUND", 409 => "CONFLICT", 429 => "RATE_LIMITED",
          500 => "INTERNAL", 503 => "UNAVAILABLE"
        }
        code = http_codes.fetch(status, "INTERNAL")
        message = "HTTP \#{status}"
        begin
          data = JSON.parse(resp.body)
          message = data["error"] if data["error"]
        rescue JSON::ParserError
          message = resp.body if resp.body && !resp.body.empty?
        end
        raise HeraldError.new(code, message, status: status)
      end

      return nil if status == 204
      return nil if resp.body.nil? || resp.body.empty?
      JSON.parse(resp.body)
    end
  end
end
`;

const STREAMS_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  class StreamNamespace
    def initialize(transport)
      @t = transport
    end

    def create(id, name, meta: nil, public: false)
      body = { id: id, name: name }
      body[:meta] = meta if meta
      body[:public] = true if public
      data = @t.request("POST", "/streams", body)
      Stream.new(**data.transform_keys(&:to_sym))
    end

    def get(id)
      data = @t.request("GET", "/streams/\#{ERB::Util.url_encode(id)}")
      Stream.new(**data.transform_keys(&:to_sym))
    end

    def update(id, name: nil, meta: nil, archived: nil)
      body = {}
      body[:name] = name if name
      body[:meta] = meta if meta
      body[:archived] = archived unless archived.nil?
      @t.request("PATCH", "/streams/\#{ERB::Util.url_encode(id)}", body)
    end

    def list
      data = @t.request("GET", "/streams")
      data["streams"].map { |r| Stream.new(**r.transform_keys(&:to_sym)) }
    end

    def delete(id)
      @t.request("DELETE", "/streams/\#{ERB::Util.url_encode(id)}")
    end
  end
end
`;

const MEMBERS_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  class MemberNamespace
    def initialize(transport)
      @t = transport
    end

    def add(stream_id, user_id, role: "member")
      data = @t.request("POST", "/streams/\#{esc(stream_id)}/members", { user_id: user_id, role: role })
      Member.new(**data.transform_keys(&:to_sym))
    end

    def list(stream_id)
      data = @t.request("GET", "/streams/\#{esc(stream_id)}/members")
      data["members"].map { |m| Member.new(**m.transform_keys(&:to_sym)) }
    end

    def remove(stream_id, user_id)
      @t.request("DELETE", "/streams/\#{esc(stream_id)}/members/\#{esc(user_id)}")
    end

    def update(stream_id, user_id, role:)
      @t.request("PATCH", "/streams/\#{esc(stream_id)}/members/\#{esc(user_id)}", { role: role })
    end

    private

    def esc(s) = ERB::Util.url_encode(s)
  end
end
`;

const EVENTS_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  class EventNamespace
    def initialize(transport)
      @t = transport
    end

    def publish(stream_id, sender:, body:, meta: nil, parent_id: nil, exclude_connection: nil)
      req = { sender: sender, body: body }
      req[:meta] = meta if meta
      req[:parent_id] = parent_id if parent_id
      req[:exclude_connection] = exclude_connection if exclude_connection
      data = @t.request("POST", "/streams/\#{esc(stream_id)}/events", req)
      EventPublishResult.new(id: data["id"], seq: data["seq"], sent_at: data["sent_at"])
    end

    def list(stream_id, before: nil, after: nil, limit: nil, thread: nil)
      params = []
      params << "before=\#{before}" if before
      params << "after=\#{after}" if after
      params << "limit=\#{limit}" if limit
      params << "thread=\#{ERB::Util.url_encode(thread)}" if thread
      qs = params.empty? ? "" : "?\#{params.join("&")}"
      data = @t.request("GET", "/streams/\#{esc(stream_id)}/events\#{qs}")
      events = data["events"].map do |m|
        Event.new(id: m["id"], stream: m["stream"] || stream_id, seq: m["seq"],
                  sender: m["sender"], body: m["body"], meta: m["meta"],
                  parent_id: m["parent_id"], edited_at: m["edited_at"], sent_at: m["sent_at"])
      end
      EventList.new(events: events, has_more: data["has_more"] || false)
    end

    # @chat Chat-specific operation — event deletion.
    def delete(stream_id, event_id)
      @t.request("DELETE", "/streams/\#{esc(stream_id)}/events/\#{esc(event_id)}")
    end

    # @chat Chat-specific operation — event editing.
    def edit(stream_id, event_id, body)
      @t.request("PATCH", "/streams/\#{esc(stream_id)}/events/\#{esc(event_id)}", { body: body })
    end

    # @chat Chat-specific operation — reaction queries.
    def get_reactions(stream_id, event_id)
      data = @t.request("GET", "/streams/\#{esc(stream_id)}/events/\#{esc(event_id)}/reactions")
      data["reactions"]
    end

    def trigger(stream_id, event, data: nil, exclude_connection: nil)
      body = { event: event }
      body[:data] = data if data
      body[:exclude_connection] = exclude_connection if exclude_connection
      @t.request("POST", "/streams/\#{esc(stream_id)}/trigger", body)
    end

    private

    def esc(s) = ERB::Util.url_encode(s)
  end
end
`;

const PRESENCE_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  # @chat Chat-specific namespace — user and stream presence queries.
  class PresenceNamespace
    def initialize(transport)
      @t = transport
    end

    def get_user(user_id)
      data = @t.request("GET", "/presence/\#{ERB::Util.url_encode(user_id)}")
      UserPresence.new(user_id: data["user_id"], status: data["status"], connections: data["connections"] || 0)
    end

    def get_stream(stream_id)
      data = @t.request("GET", "/streams/\#{ERB::Util.url_encode(stream_id)}/presence")
      data["members"].map { |m| MemberPresenceEntry.new(user_id: m["user_id"], status: m["status"]) }
    end

    def get_cursors(stream_id)
      data = @t.request("GET", "/streams/\#{ERB::Util.url_encode(stream_id)}/cursors")
      data["cursors"].map { |c| Cursor.new(user_id: c["user_id"], seq: c["seq"]) }
    end
  end
end
`;

const TENANTS_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  class TenantNamespace
    def initialize(transport)
      @t = transport
    end

    def create(name, plan: nil)
      body = { name: name }
      body[:plan] = plan if plan
      @t.request("POST", "/admin/tenants", body)
    end

    def list
      data = @t.request("GET", "/admin/tenants")
      data["tenants"]
    end

    def get(id)
      @t.request("GET", "/admin/tenants/\#{ERB::Util.url_encode(id)}")
    end

    def update(id, name: nil, plan: nil, event_ttl_days: nil)
      body = {}
      body[:name] = name if name
      body[:plan] = plan if plan
      body[:event_ttl_days] = event_ttl_days if event_ttl_days
      @t.request("PATCH", "/admin/tenants/\#{ERB::Util.url_encode(id)}", body)
    end

    def delete(id)
      @t.request("DELETE", "/admin/tenants/\#{ERB::Util.url_encode(id)}")
    end

    def create_token(tenant_id, scope: nil)
      body = scope ? { scope: scope } : nil
      data = @t.request("POST", "/admin/tenants/\#{ERB::Util.url_encode(tenant_id)}/tokens", body)
      data["token"]
    end

    def delete_token(tenant_id, token)
      @t.request("DELETE", "/admin/tenants/\#{ERB::Util.url_encode(tenant_id)}/tokens/\#{ERB::Util.url_encode(token)}")
    end

    def list_tokens(tenant_id)
      data = @t.request("GET", "/admin/tenants/\#{ERB::Util.url_encode(tenant_id)}/tokens")
      data["tokens"]
    end

    def list_streams(tenant_id)
      data = @t.request("GET", "/admin/tenants/\#{ERB::Util.url_encode(tenant_id)}/streams")
      data["streams"]
    end

    def purge_data(tenant_id)
      @t.request("DELETE", "/admin/tenants/\#{ERB::Util.url_encode(tenant_id)}/data")
    end
  end
end
`;

const BLOCKS_RB = `${HEADER}# frozen_string_literal: true

module HeraldAdmin
  # @chat Chat-specific namespace — user blocking operations.
  class BlockNamespace
    def initialize(transport)
      @t = transport
    end

    def block(user_id, blocked_id)
      @t.request("POST", "/blocks", { user_id: user_id, blocked_id: blocked_id })
    end

    def unblock(user_id, blocked_id)
      @t.request("DELETE", "/blocks", { user_id: user_id, blocked_id: blocked_id })
    end

    def list(user_id)
      data = @t.request("GET", "/blocks/\#{ERB::Util.url_encode(user_id)}")
      data["blocked"]
    end
  end
end
`;

const AUDIT_RB = `${HEADER}# frozen_string_literal: true

require "erb"

module HeraldAdmin
  class AuditNamespace
    def initialize(transport, tenant_id)
      @t = transport
      @tenant_id = tenant_id
    end

    def query(operation: nil, resource_type: nil, resource_id: nil, actor: nil, result: nil, since: nil, until_time: nil, limit: nil)
      params = build_params(
        operation: operation, resource_type: resource_type, resource_id: resource_id,
        actor: actor, result: result, since: since, until_time: until_time
      )
      params << "limit=\#{limit}" if limit
      path = base_path
      path += "?\#{params.join('&')}" unless params.empty?
      data = @t.request("GET", path)
      events = data["events"].map { |e| AuditEvent.new(**e.transform_keys(&:to_sym)) }
      AuditQueryResult.new(events: events, matched: data["matched"])
    end

    def count(operation: nil, resource_type: nil, resource_id: nil, actor: nil, result: nil, since: nil, until_time: nil)
      params = build_params(
        operation: operation, resource_type: resource_type, resource_id: resource_id,
        actor: actor, result: result, since: since, until_time: until_time
      )
      path = "\#{base_path}/count"
      path += "?\#{params.join('&')}" unless params.empty?
      data = @t.request("GET", path)
      AuditCountResult.new(count: data["count"])
    end

    private

    def base_path
      "/admin/tenants/\#{ERB::Util.url_encode(@tenant_id)}/audit"
    end

    def build_params(operation:, resource_type:, resource_id:, actor:, result:, since:, until_time:)
      params = []
      params << "operation=\#{ERB::Util.url_encode(operation)}" if operation
      params << "resource_type=\#{ERB::Util.url_encode(resource_type)}" if resource_type
      params << "resource_id=\#{ERB::Util.url_encode(resource_id)}" if resource_id
      params << "actor=\#{ERB::Util.url_encode(actor)}" if actor
      params << "result=\#{ERB::Util.url_encode(result)}" if result
      params << "since=\#{ERB::Util.url_encode(since)}" if since
      params << "until=\#{ERB::Util.url_encode(until_time)}" if until_time
      params
    end
  end
end
`;

const CLIENT_RB = `${HEADER}# frozen_string_literal: true

require "erb"

module HeraldAdmin
  # Groups chat-specific namespaces (conversational layer).
  ChatNamespaces = Struct.new(:presence, :blocks, keyword_init: true)

  class Client
    # Core namespaces (event transport)
    attr_reader :streams, :members, :events, :tenants, :audit

    # @deprecated Use {#chat}.presence instead.
    attr_reader :presence
    # @deprecated Use {#chat}.blocks instead.
    attr_reader :blocks

    # Chat-specific namespaces (conversational layer).
    # Groups presence and block operations that are part of the Herald Chat product.
    attr_reader :chat

    def initialize(url:, token: nil, key: nil, secret: nil, tenant_id: "default")
      transport = HttpTransport.new(url, token: token, key: key, secret: secret)
      @streams = StreamNamespace.new(transport)
      @members = MemberNamespace.new(transport)
      @events = EventNamespace.new(transport)
      @presence = PresenceNamespace.new(transport)
      @tenants = TenantNamespace.new(transport)
      @blocks = BlockNamespace.new(transport)
      @audit = AuditNamespace.new(transport, tenant_id)
      @chat = ChatNamespaces.new(presence: @presence, blocks: @blocks)
      @transport = transport
    end

    def health
      data = @transport.request("GET", "/health")
      HealthResponse.new(
        status: data["status"],
        connections: data["connections"] || 0,
        streams: data["streams"] || 0,
        uptime_secs: data["uptime_secs"] || 0
      )
    end

    def connections
      @transport.request("GET", "/admin/connections")
    end

    def admin_events(limit: nil)
      path = "/admin/events"
      path += "?limit=\#{limit}" if limit
      @transport.request("GET", path)
    end

    def errors(limit: nil, category: nil)
      params = []
      params << "limit=\#{limit}" if limit
      params << "category=\#{ERB::Util.url_encode(category)}" if category
      path = "/admin/errors"
      path += "?\#{params.join('&')}" unless params.empty?
      @transport.request("GET", path)
    end

    def stats
      @transport.request("GET", "/admin/stats")
    end
  end
end
`;

const HERALD_ADMIN_RB = `${HEADER}# frozen_string_literal: true

require_relative "herald_admin/errors"
require_relative "herald_admin/types"
require_relative "herald_admin/transport"
require_relative "herald_admin/streams"
require_relative "herald_admin/members"
require_relative "herald_admin/events"
require_relative "herald_admin/presence"
require_relative "herald_admin/tenants"
require_relative "herald_admin/blocks"
require_relative "herald_admin/audit"
require_relative "herald_admin/client"
`;

export function emitRuby(sdk: SdkDefinition, outDir: string): void {
  const libDir = join(outDir, "lib");
  const haDir = join(libDir, "herald_admin");
  mkdirSync(haDir, { recursive: true });

  writeFileSync(join(libDir, "herald_admin.rb"), HERALD_ADMIN_RB);
  writeFileSync(join(haDir, "errors.rb"), ERRORS_RB);
  writeFileSync(join(haDir, "types.rb"), TYPES_RB);
  writeFileSync(join(haDir, "transport.rb"), TRANSPORT_RB);
  writeFileSync(join(haDir, "streams.rb"), STREAMS_RB);
  writeFileSync(join(haDir, "members.rb"), MEMBERS_RB);
  writeFileSync(join(haDir, "events.rb"), EVENTS_RB);
  writeFileSync(join(haDir, "presence.rb"), PRESENCE_RB);
  writeFileSync(join(haDir, "tenants.rb"), TENANTS_RB);
  writeFileSync(join(haDir, "blocks.rb"), BLOCKS_RB);
  writeFileSync(join(haDir, "audit.rb"), AUDIT_RB);
  writeFileSync(join(haDir, "client.rb"), CLIENT_RB);

  console.log(`  Ruby: wrote 12 files to ${libDir}`);
}
