// TypeScript admin SDK emitter.
// Generates code matching the herald-admin-typescript package structure.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { Method, Namespace, RootMethod, SdkDefinition } from "../ir.ts";

const HEADER = "// Code generated by codegen/generate.ts — DO NOT EDIT.\n\n";

// ---- Type definitions ----
// These are hand-maintained because the OpenAPI schema types don't cleanly map
// to the lean interfaces the SDK exposes (e.g. EventView vs Event, tenant
// response variants). We emit them verbatim.

const TYPES_TS = `${HEADER}export interface Stream {
  id: string;
  name: string;
  meta?: unknown;
  created_at: number;
  public?: boolean;
  archived?: boolean;
}

export interface Member {
  stream_id: string;
  user_id: string;
  role: string;
  joined_at: number;
}

export interface Event {
  id: string;
  stream: string;
  seq: number;
  sender: string;
  body: string;
  meta?: unknown;
  sent_at: number;
  parent_id?: string;
  edited_at?: number;
}

export interface BlockList {
  blocked: string[];
}

export interface EventList {
  events: Event[];
  has_more: boolean;
}

export interface UserPresence {
  user_id: string;
  status: string;
  connections: number;
}

export interface MemberPresenceEntry {
  user_id: string;
  status: string;
}

export interface HealthResponse {
  status: string;
  connections: number;
  streams: number;
  uptime_secs: number;
}

export interface EventPublishResult {
  id: string;
  seq: number;
  sent_at: number;
}

export interface AuditEvent {
  id: string;
  timestamp: number;
  operation: string;
  resource_type: string;
  resource_id: string;
  actor: string;
  result: string;
  tenant_id: string;
  diff?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

export interface AuditQueryResponse {
  events: AuditEvent[];
  matched: number;
}

export interface AuditCountResponse {
  count: number;
}

export interface AuditQueryOptions {
  operation?: string;
  resource_type?: string;
  resource_id?: string;
  actor?: string;
  result?: string;
  since?: string;
  until?: string;
  limit?: number;
}

export interface AuditCountOptions {
  operation?: string;
  resource_type?: string;
  resource_id?: string;
  actor?: string;
  result?: string;
  since?: string;
  until?: string;
}

export interface ConnectionInfo {
  total: number;
  by_tenant: Array<{ tenant_id: string; connections: number }>;
}

export interface AdminEventEntry {
  id: number;
  kind: string;
  tenant_id?: string;
  stream_id?: string;
  user_id?: string;
  detail?: string;
  timestamp: number;
}

export interface AdminEventList {
  events: AdminEventEntry[];
}

export interface AdminErrorEntry {
  id: number;
  category: string;
  message: string;
  detail?: string;
  timestamp: number;
}

export interface AdminErrorList {
  errors: AdminErrorEntry[];
}

export interface StatsSnapshot {
  timestamp: number;
  connections: number;
  events_published: number;
  webhooks_sent: number;
  streams: number;
}

export interface AdminStats {
  today: StatsSnapshot;
  snapshots: StatsSnapshot[];
}

export interface TenantStats {
  current: {
    connections: number;
    events_published: number;
    webhooks_sent: number;
    streams: number;
  };
  snapshots: StatsSnapshot[];
}
`;

const ERRORS_TS = `${HEADER}export class HeraldError extends Error {
  public readonly code: string;
  public readonly status: number;

  constructor(code: string, message: string, status: number) {
    super(\`\${code}: \${message}\`);
    this.code = code;
    this.status = status;
    this.name = "HeraldError";
  }
}
`;

const TRANSPORT_TS = `${HEADER}import { HeraldError } from "./errors.js";

const HTTP_ERROR_CODES: Record<number, string> = {
  400: "BAD_REQUEST",
  401: "UNAUTHORIZED",
  403: "FORBIDDEN",
  404: "NOT_FOUND",
  409: "CONFLICT",
  429: "RATE_LIMITED",
  500: "INTERNAL",
  503: "UNAVAILABLE",
};

export class HttpTransport {
  private baseUrl: string;
  private authHeader: string;
  private timeoutMs: number;

  constructor(baseUrl: string, auth: { token: string } | { key: string; secret: string }, timeoutMs?: number) {
    this.baseUrl = baseUrl.replace(/\\/$/, "");
    this.authHeader = "token" in auth
      ? \`Bearer \${auth.token}\`
      : \`Basic \${btoa(\`\${auth.key}:\${auth.secret}\`)}\`;
    this.timeoutMs = timeoutMs ?? 30_000;
  }

  async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const headers: Record<string, string> = {
      Authorization: this.authHeader,
    };
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
    }
    if (extraHeaders) {
      Object.assign(headers, extraHeaders);
    }

    const signal = AbortSignal.timeout(this.timeoutMs);

    const resp = await fetch(\`\${this.baseUrl}\${path}\`, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
      signal,
    });

    if (!resp.ok) {
      const code = HTTP_ERROR_CODES[resp.status] ?? "INTERNAL";
      let message = \`HTTP \${resp.status}\`;
      try {
        const json = (await resp.json()) as Record<string, string>;
        if (json.error) {
          message = json.error;
        }
      } catch {
        const text = await resp.text().catch(() => "");
        if (text) message = text;
      }
      throw new HeraldError(code, message, resp.status);
    }

    const contentLength = resp.headers.get("content-length");
    if (resp.status === 204 || contentLength === "0") {
      return undefined as T;
    }

    const text = await resp.text();
    if (!text) return undefined as T;
    return JSON.parse(text) as T;
  }
}
`;

// ---- Emitter helpers ----

function enc(paramName: string): string {
  return `encodeURIComponent(${paramName})`;
}

function buildPath(template: string, pathParams: { name: string; wireName: string }[]): string {
  let result = template;
  for (const p of pathParams) {
    result = result.replace(`{${p.wireName}}`, `\${${enc(p.name)}}`);
  }
  return `\`${result}\``;
}

// ---- Namespace emitters ----

function emitStreamsNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";
import type { Stream } from "../types.js";

export class StreamNamespace {
  constructor(private transport: HttpTransport) {}

  async list(): Promise<Stream[]> {
    const res = await this.transport.request<{ streams: Stream[] }>("GET", "/streams");
    return res.streams;
  }

  async create(
    id: string,
    name: string,
    options?: { meta?: unknown; public?: boolean },
  ): Promise<Stream> {
    return this.transport.request<Stream>("POST", "/streams", {
      id,
      name,
      meta: options?.meta,
      public: options?.public,
    });
  }

  async get(id: string): Promise<Stream> {
    return this.transport.request<Stream>("GET", \`/streams/\${encodeURIComponent(id)}\`);
  }

  async update(id: string, options: { name?: string; meta?: unknown; archived?: boolean }): Promise<void> {
    return this.transport.request("PATCH", \`/streams/\${encodeURIComponent(id)}\`, options);
  }

  async delete(id: string): Promise<void> {
    return this.transport.request("DELETE", \`/streams/\${encodeURIComponent(id)}\`);
  }
}
`;
}

function emitMembersNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";
import type { Member } from "../types.js";

export class MemberNamespace {
  constructor(private transport: HttpTransport) {}

  async add(streamId: string, userId: string, role?: string): Promise<Member> {
    return this.transport.request<Member>(
      "POST",
      \`/streams/\${encodeURIComponent(streamId)}/members\`,
      { user_id: userId, role },
    );
  }

  async list(streamId: string): Promise<Member[]> {
    const resp = await this.transport.request<{ members: Member[] }>(
      "GET",
      \`/streams/\${encodeURIComponent(streamId)}/members\`,
    );
    return resp.members;
  }

  async remove(streamId: string, userId: string): Promise<void> {
    return this.transport.request(
      "DELETE",
      \`/streams/\${encodeURIComponent(streamId)}/members/\${encodeURIComponent(userId)}\`,
    );
  }

  async update(streamId: string, userId: string, role: string): Promise<void> {
    return this.transport.request(
      "PATCH",
      \`/streams/\${encodeURIComponent(streamId)}/members/\${encodeURIComponent(userId)}\`,
      { role },
    );
  }
}
`;
}

function emitEventsNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";
import type { EventList, EventPublishResult } from "../types.js";

export class EventNamespace {
  constructor(private transport: HttpTransport) {}

  async publish(
    streamId: string,
    sender: string,
    body: string,
    options?: { meta?: unknown; parentId?: string; excludeConnection?: string },
  ): Promise<EventPublishResult> {
    const headers: Record<string, string> = {};
    if (options?.excludeConnection) {
      headers["X-Exclude-Connection"] = options.excludeConnection;
    }
    return this.transport.request<EventPublishResult>(
      "POST",
      \`/streams/\${encodeURIComponent(streamId)}/events\`,
      { sender, body, meta: options?.meta, parent_id: options?.parentId },
      headers,
    );
  }

  async list(
    streamId: string,
    options?: { before?: number; after?: number; limit?: number; thread?: string },
  ): Promise<EventList> {
    const params = new URLSearchParams();
    if (options?.before !== undefined) params.set("before", String(options.before));
    if (options?.after !== undefined) params.set("after", String(options.after));
    if (options?.limit !== undefined) params.set("limit", String(options.limit));
    if (options?.thread !== undefined) params.set("thread", options.thread);
    const qs = params.toString();
    const path = \`/streams/\${encodeURIComponent(streamId)}/events\${qs ? \`?\${qs}\` : ""}\`;
    return this.transport.request<EventList>("GET", path);
  }

  async trigger(streamId: string, event: string, data?: unknown, excludeConnection?: number): Promise<void> {
    const body: Record<string, unknown> = { event };
    if (data !== undefined) body.data = data;
    if (excludeConnection !== undefined) body.exclude_connection = excludeConnection;
    await this.transport.request("POST", \`/streams/\${encodeURIComponent(streamId)}/trigger\`, body);
  }

}
`;
}

function emitTenantsNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";
import type { Stream } from "../types.js";

export interface Tenant {
  id: string;
  name: string;
  plan: string;
  key: string;
  created_at: number;
}

export interface TenantWithSecret extends Tenant {
  secret: string;
}

export interface CreateTenantOptions {
  name: string;
  plan?: string;
}

export interface ApiToken {
  token: string;
  scope?: string | null;
}

export class TenantNamespace {
  constructor(private transport: HttpTransport) {}

  async create(opts: CreateTenantOptions): Promise<TenantWithSecret> {
    return this.transport.request<TenantWithSecret>("POST", "/admin/tenants", opts);
  }

  async list(): Promise<Tenant[]> {
    const res = await this.transport.request<{ tenants: Tenant[] }>("GET", "/admin/tenants");
    return res.tenants;
  }

  async get(id: string): Promise<Tenant> {
    return this.transport.request<Tenant>("GET", \`/admin/tenants/\${encodeURIComponent(id)}\`);
  }

  async update(id: string, opts: { name?: string; plan?: string; config?: unknown; event_ttl_days?: number }): Promise<void> {
    await this.transport.request("PATCH", \`/admin/tenants/\${encodeURIComponent(id)}\`, opts);
  }

  async delete(id: string): Promise<void> {
    await this.transport.request("DELETE", \`/admin/tenants/\${encodeURIComponent(id)}\`);
  }

  async createToken(tenantId: string, scope?: string): Promise<ApiToken> {
    const body = scope ? { scope } : undefined;
    return this.transport.request<ApiToken>("POST", \`/admin/tenants/\${encodeURIComponent(tenantId)}/tokens\`, body);
  }

  async listTokens(tenantId: string): Promise<ApiToken[]> {
    const res = await this.transport.request<{ tokens: ApiToken[] }>("GET", \`/admin/tenants/\${encodeURIComponent(tenantId)}/tokens\`);
    return res.tokens;
  }

  async deleteToken(tenantId: string, token: string): Promise<void> {
    await this.transport.request("DELETE", \`/admin/tenants/\${encodeURIComponent(tenantId)}/tokens/\${encodeURIComponent(token)}\`);
  }

  async listTenantStreams(tenantId: string): Promise<Stream[]> {
    const res = await this.transport.request<{ streams: Stream[] }>("GET", \`/admin/tenants/\${encodeURIComponent(tenantId)}/streams\`);
    return res.streams;
  }

  async purgeData(tenantId: string): Promise<{ deleted: number }> {
    return this.transport.request<{ deleted: number }>("DELETE", \`/admin/tenants/\${encodeURIComponent(tenantId)}/data\`);
  }
}
`;
}

function emitAuditNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";
import type { AuditQueryOptions, AuditQueryResponse, AuditCountOptions, AuditCountResponse } from "../types.js";

export class AuditNamespace {
  constructor(
    private transport: HttpTransport,
    private tenantId: string,
  ) {}

  private buildParams(opts?: AuditQueryOptions | AuditCountOptions): string {
    if (!opts) return "";
    const params = new URLSearchParams();
    if (opts.operation != null) params.set("operation", opts.operation);
    if (opts.resource_type != null) params.set("resource_type", opts.resource_type);
    if (opts.resource_id != null) params.set("resource_id", opts.resource_id);
    if (opts.actor != null) params.set("actor", opts.actor);
    if (opts.result != null) params.set("result", opts.result);
    if (opts.since != null) params.set("since", opts.since);
    if (opts.until != null) params.set("until", opts.until);
    if ("limit" in opts && opts.limit != null) params.set("limit", String(opts.limit));
    const qs = params.toString();
    return qs ? \`?\${qs}\` : "";
  }

  private basePath(): string {
    return \`/admin/tenants/\${encodeURIComponent(this.tenantId)}/audit\`;
  }

  async query(opts?: AuditQueryOptions): Promise<AuditQueryResponse> {
    return this.transport.request<AuditQueryResponse>(
      "GET",
      \`\${this.basePath()}\${this.buildParams(opts)}\`,
    );
  }

  async count(opts?: AuditCountOptions): Promise<AuditCountResponse> {
    return this.transport.request<AuditCountResponse>(
      "GET",
      \`\${this.basePath()}/count\${this.buildParams(opts)}\`,
    );
  }
}
`;
}

function emitPresenceNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";
import type { MemberPresenceEntry, UserPresence } from "../types.js";

export class PresenceNamespace {
  constructor(private transport: HttpTransport) {}

  async getUser(userId: string): Promise<UserPresence> {
    return this.transport.request<UserPresence>(
      "GET",
      \`/presence/\${encodeURIComponent(userId)}\`,
    );
  }

  async getStream(streamId: string): Promise<MemberPresenceEntry[]> {
    const resp = await this.transport.request<{ members: MemberPresenceEntry[] }>(
      "GET",
      \`/streams/\${encodeURIComponent(streamId)}/presence\`,
    );
    return resp.members;
  }

  async getBulk(userIds: string[]): Promise<UserPresence[]> {
    const ids = userIds.map(encodeURIComponent).join(",");
    const resp = await this.transport.request<{ users: UserPresence[] }>(
      "GET",
      \`/presence?user_ids=\${ids}\`,
    );
    return resp.users;
  }

  async setOverride(userId: string, options: { status: string; until?: string }): Promise<UserPresence> {
    return this.transport.request<UserPresence>(
      "POST",
      \`/presence/\${encodeURIComponent(userId)}\`,
      options,
    );
  }
}
`;
}

function emitBlocksNamespace(_ns: Namespace): string {
  return `${HEADER}import type { HttpTransport } from "../transport.js";

export class BlockNamespace {
  constructor(private transport: HttpTransport) {}

  async block(userId: string, blockedId: string): Promise<void> {
    await this.transport.request("POST", "/blocks", { user_id: userId, blocked_id: blockedId });
  }

  async unblock(userId: string, blockedId: string): Promise<void> {
    await this.transport.request("DELETE", "/blocks", { user_id: userId, blocked_id: blockedId });
  }

  async list(userId: string): Promise<string[]> {
    const res = await this.transport.request<{ blocked: string[] }>("GET", \`/blocks/\${encodeURIComponent(userId)}\`);
    return res.blocked;
  }
}
`;
}

const NS_EMITTERS: Record<string, (ns: Namespace) => string> = {
  streams: emitStreamsNamespace,
  members: emitMembersNamespace,
  events: emitEventsNamespace,
  tenants: emitTenantsNamespace,
  audit: emitAuditNamespace,
  presence: emitPresenceNamespace,
  blocks: emitBlocksNamespace,
};

// File name mapping — matches the existing hand-rolled file names
const NS_FILENAMES: Record<string, string> = {
  streams: "rooms.ts",
  members: "members.ts",
  events: "messages.ts",
  tenants: "tenants.ts",
  audit: "audit.ts",
  presence: "presence.ts",
  blocks: "blocks.ts",
};

function emitClient(_sdk: SdkDefinition): string {
  return `${HEADER}import { HttpTransport } from "./transport.js";
import { AuditNamespace } from "./namespaces/audit.js";
import { MemberNamespace } from "./namespaces/members.js";
import { EventNamespace } from "./namespaces/messages.js";
import { PresenceNamespace } from "./namespaces/presence.js";
import { StreamNamespace } from "./namespaces/rooms.js";
import { TenantNamespace } from "./namespaces/tenants.js";
import { BlockNamespace } from "./namespaces/blocks.js";
import type {
  AdminEventList,
  AdminErrorList,
  AdminStats,
  ConnectionInfo,
  HealthResponse,
  TenantStats,
} from "./types.js";

export type HeraldAdminOptions = {
  /** Herald HTTP API URL, e.g. http://localhost:6201 */
  url: string;
  /** Tenant ID for tenant-scoped namespaces (audit). */
  tenantId?: string;
  /** Request timeout in milliseconds. Default 30000. */
  timeoutMs?: number;
} & (
  | { /** API bearer token. */ token: string; key?: never; secret?: never }
  | { /** Tenant key for Basic auth. */ key: string; /** Tenant secret for Basic auth. */ secret: string; token?: never }
);

export interface AdminEventListOptions {
  limit?: number;
}

export interface ErrorListOptions {
  limit?: number;
  category?: string;
}

/**
 * Herald HTTP admin client for backend services.
 *
 * Provides namespaced access to Herald's HTTP API for stream management,
 * member management, event publishing, and presence queries.
 */
export class HeraldAdmin {
  // --- Core namespaces (event transport) ---
  public readonly streams: StreamNamespace;
  public readonly members: MemberNamespace;
  public readonly events: EventNamespace;
  public readonly tenants: TenantNamespace;
  public readonly audit: AuditNamespace | undefined;

  /** Presence queries and admin overrides. */
  public readonly presence: PresenceNamespace;

  /** Chat-specific namespaces (conversational layer). */
  public readonly chat: {
    readonly blocks: BlockNamespace;
  };

  private transport: HttpTransport;

  constructor(options: HeraldAdminOptions) {
    const auth = options.token
      ? { token: options.token }
      : { key: options.key!, secret: options.secret! };
    this.transport = new HttpTransport(options.url, auth, options.timeoutMs);
    this.streams = new StreamNamespace(this.transport);
    this.members = new MemberNamespace(this.transport);
    this.events = new EventNamespace(this.transport);
    this.tenants = new TenantNamespace(this.transport);
    this.presence = new PresenceNamespace(this.transport);
    this.chat = {
      blocks: new BlockNamespace(this.transport),
    };
    this.audit = options.tenantId
      ? new AuditNamespace(this.transport, options.tenantId)
      : undefined;
  }

  async health(): Promise<HealthResponse> {
    return this.transport.request<HealthResponse>("GET", "/health");
  }

  async connections(): Promise<ConnectionInfo> {
    return this.transport.request<ConnectionInfo>("GET", "/admin/connections");
  }

  async adminEvents(opts?: AdminEventListOptions): Promise<AdminEventList> {
    let path = "/admin/events";
    if (opts?.limit != null) {
      path += \`?limit=\${opts.limit}\`;
    }
    return this.transport.request<AdminEventList>("GET", path);
  }

  async errors(opts?: ErrorListOptions): Promise<AdminErrorList> {
    const params = new URLSearchParams();
    if (opts?.limit != null) params.set("limit", String(opts.limit));
    if (opts?.category) params.set("category", opts.category);
    const qs = params.toString();
    return this.transport.request<AdminErrorList>("GET", \`/admin/errors\${qs ? \`?\${qs}\` : ""}\`);
  }

  async stats(): Promise<AdminStats> {
    return this.transport.request<AdminStats>("GET", "/admin/stats");
  }

  async tenantStats(): Promise<TenantStats> {
    return this.transport.request<TenantStats>("GET", "/stats");
  }
}
`;
}

function emitIndex(_sdk: SdkDefinition): string {
  return `${HEADER}export { HeraldAdmin, type HeraldAdminOptions, type AdminEventListOptions, type ErrorListOptions } from "./client.js";
export { HeraldError } from "./errors.js";
export { AuditNamespace } from "./namespaces/audit.js";
export { StreamNamespace } from "./namespaces/rooms.js";
export { MemberNamespace } from "./namespaces/members.js";
export { EventNamespace } from "./namespaces/messages.js";
export { PresenceNamespace } from "./namespaces/presence.js";
export { TenantNamespace, type Tenant, type TenantWithSecret, type CreateTenantOptions, type ApiToken } from "./namespaces/tenants.js";
export { BlockNamespace } from "./namespaces/blocks.js";
export type {
  Stream,
  Member,
  Event,
  EventList,
  UserPresence,
  MemberPresenceEntry,
  HealthResponse,
  EventPublishResult,
  BlockList,
  AuditEvent,
  AuditQueryResponse,
  AuditCountResponse,
  AuditQueryOptions,
  AuditCountOptions,
  ConnectionInfo,
  AdminEventEntry,
  AdminEventList,
  AdminErrorEntry,
  AdminErrorList,
  StatsSnapshot,
  AdminStats,
  TenantStats,
} from "./types.js";
`;
}

// ---- Main emitter ----

export function emitTypeScript(sdk: SdkDefinition, outDir: string): void {
  const srcDir = join(outDir, "src");
  const nsDir = join(srcDir, "namespaces");
  mkdirSync(nsDir, { recursive: true });

  // Static files
  writeFileSync(join(srcDir, "types.ts"), TYPES_TS);
  writeFileSync(join(srcDir, "errors.ts"), ERRORS_TS);
  writeFileSync(join(srcDir, "transport.ts"), TRANSPORT_TS);

  // Namespace files
  for (const ns of sdk.namespaces) {
    const emitter = NS_EMITTERS[ns.id];
    if (!emitter) {
      console.warn(`No TypeScript emitter for namespace: ${ns.id}`);
      continue;
    }
    const filename = NS_FILENAMES[ns.id] ?? `${ns.id}.ts`;
    writeFileSync(join(nsDir, filename), emitter(ns));
  }

  // Client
  writeFileSync(join(srcDir, "client.ts"), emitClient(sdk));

  // Index
  writeFileSync(join(srcDir, "index.ts"), emitIndex(sdk));

  console.log(`  TypeScript: wrote ${7 + sdk.namespaces.length} files to ${srcDir}`);
}
