// Code generated by codegen/generate.ts — DO NOT EDIT.

import { HttpTransport } from "./transport.js";
import { AuditNamespace } from "./namespaces/audit.js";
import { MemberNamespace } from "./namespaces/members.js";
import { EventNamespace } from "./namespaces/messages.js";
import { PresenceNamespace } from "./namespaces/presence.js";
import { StreamNamespace } from "./namespaces/rooms.js";
import { TenantNamespace } from "./namespaces/tenants.js";
import { BlockNamespace } from "./namespaces/blocks.js";
import type {
  AdminEventList,
  AdminErrorList,
  AdminStats,
  ConnectionInfo,
  HealthResponse,
  TenantStats,
} from "./types.js";

export type HeraldAdminOptions = {
  /** Herald HTTP API URL, e.g. http://localhost:6201 */
  url: string;
  /** Tenant ID for tenant-scoped namespaces (audit). */
  tenantId?: string;
  /** Request timeout in milliseconds. Default 30000. */
  timeoutMs?: number;
} & (
  | { /** API bearer token. */ token: string; key?: never; secret?: never }
  | { /** Tenant key for Basic auth. */ key: string; /** Tenant secret for Basic auth. */ secret: string; token?: never }
);

export interface AdminEventListOptions {
  limit?: number;
}

export interface ErrorListOptions {
  limit?: number;
  category?: string;
}

/**
 * Herald HTTP admin client for backend services.
 *
 * Provides namespaced access to Herald's HTTP API for stream management,
 * member management, event publishing, and presence queries.
 */
export class HeraldAdmin {
  // --- Core namespaces (event transport) ---
  public readonly streams: StreamNamespace;
  public readonly members: MemberNamespace;
  public readonly events: EventNamespace;
  public readonly tenants: TenantNamespace;
  public readonly audit: AuditNamespace | undefined;

  /**
   * Chat-specific namespaces (conversational layer).
   * Groups presence and block operations that are part of the Herald Chat product.
   */
  public readonly chat: {
    readonly presence: PresenceNamespace;
    readonly blocks: BlockNamespace;
  };

  private transport: HttpTransport;

  constructor(options: HeraldAdminOptions) {
    const auth = options.token
      ? { token: options.token }
      : { key: options.key!, secret: options.secret! };
    this.transport = new HttpTransport(options.url, auth, options.timeoutMs);
    this.streams = new StreamNamespace(this.transport);
    this.members = new MemberNamespace(this.transport);
    this.events = new EventNamespace(this.transport);
    this.tenants = new TenantNamespace(this.transport);
    this.chat = {
      presence: new PresenceNamespace(this.transport),
      blocks: new BlockNamespace(this.transport),
    };
    this.audit = options.tenantId
      ? new AuditNamespace(this.transport, options.tenantId)
      : undefined;
  }

  async health(): Promise<HealthResponse> {
    return this.transport.request<HealthResponse>("GET", "/health");
  }

  async connections(): Promise<ConnectionInfo> {
    return this.transport.request<ConnectionInfo>("GET", "/admin/connections");
  }

  async adminEvents(opts?: AdminEventListOptions): Promise<AdminEventList> {
    let path = "/admin/events";
    if (opts?.limit != null) {
      path += `?limit=${opts.limit}`;
    }
    return this.transport.request<AdminEventList>("GET", path);
  }

  async errors(opts?: ErrorListOptions): Promise<AdminErrorList> {
    const params = new URLSearchParams();
    if (opts?.limit != null) params.set("limit", String(opts.limit));
    if (opts?.category) params.set("category", opts.category);
    const qs = params.toString();
    return this.transport.request<AdminErrorList>("GET", `/admin/errors${qs ? `?${qs}` : ""}`);
  }

  async stats(): Promise<AdminStats> {
    return this.transport.request<AdminStats>("GET", "/admin/stats");
  }

  async tenantStats(): Promise<TenantStats> {
    return this.transport.request<TenantStats>("GET", "/stats");
  }
}
