// Code generated by codegen/generate.ts — DO NOT EDIT.

export interface Stream {
  id: string;
  name: string;
  meta?: unknown;
  created_at: number;
  public?: boolean;
  archived?: boolean;
}

export interface Member {
  stream_id: string;
  user_id: string;
  role: string;
  joined_at: number;
}

export interface Event {
  id: string;
  stream: string;
  seq: number;
  sender: string;
  body: string;
  meta?: unknown;
  sent_at: number;
  parent_id?: string;
  edited_at?: number;
}

export interface ReactionSummary {
  emoji: string;
  count: number;
  users: string[];
}

export interface BlockList {
  blocked: string[];
}

export interface EventList {
  events: Event[];
  has_more: boolean;
}

export interface UserPresence {
  user_id: string;
  status: string;
  connections: number;
}

export interface MemberPresenceEntry {
  user_id: string;
  status: string;
}

export interface Cursor {
  user_id: string;
  seq: number;
}

export interface HealthResponse {
  status: string;
  connections: number;
  streams: number;
  uptime_secs: number;
}

export interface EventPublishResult {
  id: string;
  seq: number;
  sent_at: number;
}

export interface AuditEvent {
  id: string;
  timestamp: number;
  operation: string;
  resource_type: string;
  resource_id: string;
  actor: string;
  result: string;
  tenant_id: string;
  diff?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

export interface AuditQueryResponse {
  events: AuditEvent[];
  matched: number;
}

export interface AuditCountResponse {
  count: number;
}

export interface AuditQueryOptions {
  operation?: string;
  resource_type?: string;
  resource_id?: string;
  actor?: string;
  result?: string;
  since?: string;
  until?: string;
  limit?: number;
}

export interface AuditCountOptions {
  operation?: string;
  resource_type?: string;
  resource_id?: string;
  actor?: string;
  result?: string;
  since?: string;
  until?: string;
}

export interface ConnectionInfo {
  total: number;
  by_tenant: Array<{ tenant_id: string; connections: number }>;
}

export interface AdminEventEntry {
  id: number;
  kind: string;
  tenant_id?: string;
  stream_id?: string;
  user_id?: string;
  detail?: string;
  timestamp: number;
}

export interface AdminEventList {
  events: AdminEventEntry[];
}

export interface AdminErrorEntry {
  id: number;
  category: string;
  message: string;
  detail?: string;
  timestamp: number;
}

export interface AdminErrorList {
  errors: AdminErrorEntry[];
}

export interface StatsSnapshot {
  timestamp: number;
  connections: number;
  events_published: number;
  webhooks_sent: number;
  streams: number;
}

export interface AdminStats {
  today: StatsSnapshot;
  snapshots: StatsSnapshot[];
}

export interface TenantStats {
  current: {
    connections: number;
    events_published: number;
    webhooks_sent: number;
    streams: number;
  };
  snapshots: StatsSnapshot[];
}
